"""Generated by AetherLab - standing wave (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        n = 3
        title = Text('Show a standing wave forming from two travelling waves on a…').scale(0.46).to_edge(UP)

        length = 10.0
        amp = 1.4
        x0 = -length / 2.0

        def y_of(x, phase):
            xi = x - x0
            return amp * np.sin(n * PI * xi / length) * np.cos(phase)

        axis = Line([x0, 0, 0], [x0 + length, 0, 0], color=GREY_B,
                    stroke_width=2, stroke_opacity=0.5)
        wall_l = Line([x0, -1.8, 0], [x0, 1.8, 0], color=GREY_A, stroke_width=5)
        wall_r = Line([x0 + length, -1.8, 0], [x0 + length, 1.8, 0], color=GREY_A, stroke_width=5)

        grid = np.linspace(x0, x0 + length, 160)
        phase = ValueTracker(0.0)

        def string():
            pts = [np.array([x, y_of(x, phase.get_value()), 0.0]) for x in grid]
            m = VMobject(color=TEAL, stroke_width=4)
            m.set_points_smoothly(pts)
            return m

        wave = always_redraw(string)
        # Envelope (the standing-wave amplitude profile) as a dashed ghost.
        env_hi = DashedVMobject(VMobject(color=BLUE_C, stroke_width=2).set_points_smoothly(
            [np.array([x, abs(amp * np.sin(n * PI * (x - x0) / length)), 0.0]) for x in grid]))
        env_lo = DashedVMobject(VMobject(color=BLUE_C, stroke_width=2).set_points_smoothly(
            [np.array([x, -abs(amp * np.sin(n * PI * (x - x0) / length)), 0.0]) for x in grid]))

        # Nodes (fixed) and antinodes (max swing).
        nodes = VGroup(*[Dot([x0 + length * k / n, 0, 0], color=RED, radius=0.07)
                         for k in range(n + 1)])
        antinodes = VGroup(*[Dot([x0 + length * (k + 0.5) / n, 0, 0], color=YELLOW, radius=0.06)
                             for k in range(n)])
        node_lbl = Text("nodes (fixed)", color=RED).scale(0.3).to_corner(DL, buff=0.6)

        self.play(FadeIn(title), Create(axis), Create(wall_l), Create(wall_r), run_time=1.0)
        self.play(Create(env_hi), Create(env_lo), run_time=0.9)
        self.add(wave)
        self.play(LaggedStart(*[GrowFromCenter(d) for d in nodes], lag_ratio=0.1),
                  FadeIn(node_lbl), run_time=1.0)
        self.add(antinodes)
        self.play(phase.animate.set_value(3.0 * TAU), run_time=6.0, rate_func=linear)
        self.wait(0.4)
