"""Generated by AetherLab - Fourier epicycles (curated component)."""

import math

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Building a square wave from sine waves', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('f(x) = (4/π)·Σ sin(n·x)/n, n = 1, 3, 5, ...', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: each rotating circle is one harmonic; the tip\nof the chain draws the wave.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.0)
        self.wait(1.8)
        self.play(FadeOut(_intro), run_time=0.5)

        # AetherLab explanation layer: predict before the reveal.
        _pq_head = Text('Predict first', font_size=34, weight=BOLD, color=YELLOW)
        _pq_text = Text('Add more and more circles. Does the bump at each\ncorner of the square wave go away?', font_size=30, color=WHITE)
        _pq_hint = Text('Decide before you watch.', font_size=24, color=GREY_B)
        _pq_bar = Line(3 * LEFT, 3 * RIGHT, color=YELLOW, stroke_width=6)
        _pq_card = VGroup(_pq_head, _pq_text, _pq_hint, _pq_bar).arrange(DOWN, buff=0.45)
        if _pq_card.width > 12.4:
            _pq_card.scale_to_fit_width(12.4)
        if _pq_card.height > 7.0:
            _pq_card.scale_to_fit_height(7.0)
        self.play(FadeIn(_pq_card, shift=0.2 * UP), run_time=0.8)
        self.play(_pq_bar.animate.scale(0.01, about_edge=LEFT), run_time=2.5, rate_func=linear)
        self.play(FadeOut(_pq_card), run_time=0.5)

        # AetherLab explanation layer: timed captions during the animation, with a
        # highlight ring and pointer on the object each caption describes.
        _clock = ValueTracker(0.0)
        _clock.add_updater(lambda m, dt: m.increment_value(dt))
        self.add(_clock)

        def _cap_alpha(t, a, b):
            return max(0.0, min(1.0, (t - a) / 0.35, (b - t) / 0.35))

        def _cap_pointer(cap, target, alpha):
            end = target.get_center()
            ring = Circle(radius=0.32, color=YELLOW_A, stroke_width=3).move_to(end)
            ring.set_stroke(opacity=alpha)
            start = cap.get_bottom() + 0.12 * DOWN
            if np.linalg.norm(end - start) < 0.9:
                return VGroup(ring).set_z_index(19)
            line = DashedLine(start, end, buff=0.36, color=YELLOW_A, stroke_width=2)
            line.set_stroke(opacity=0.8 * alpha)
            return VGroup(line, ring).set_z_index(19)

        def _cap_point_update(m, cap, target_fn, a, b):
            # The target is looked up lazily: it is only created by the
            # animation below, after this setup code has run.
            alpha = _cap_alpha(_clock.get_value(), a, b)
            if alpha <= 0:
                m.set_stroke(opacity=0)
                return
            try:
                target = target_fn()
            except NameError:
                return
            # Refresh the target first; otherwise the ring trails a moving
            # object by one frame (this updater can run before the target's).
            target.update(0)
            m.become(_cap_pointer(cap, target, alpha))

        _cap_band = Rectangle(width=14.6, height=1.0, stroke_width=0, fill_color=BLACK, fill_opacity=0.0).to_edge(UP, buff=0).set_z_index(20)
        _cap_band.add_updater(lambda m: m.set_fill(BLACK, opacity=_cap_alpha(_clock.get_value(), 1.3, 9.2)))
        self.add(_cap_band)
        _cap_mobs = []
        _cap_0 = Text('Each circle spins at its own harmonic speed', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_0.width > 13.4:
            _cap_0.scale_to_fit_width(13.4)
        if _cap_0.height > 0.9:
            _cap_0.scale_to_fit_height(0.9)
        _cap_0.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 1.3, 3.8)))
        _cap_mobs.append(_cap_0)
        _ptr_0 = VGroup().set_z_index(19)
        _ptr_0.add_updater(lambda m: _cap_point_update(m, _cap_0, lambda: phasors, 1.3, 3.8))
        _cap_mobs.append(_ptr_0)
        _cap_1 = Text("The chain's tip draws the sum", font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_1.width > 13.4:
            _cap_1.scale_to_fit_width(13.4)
        if _cap_1.height > 0.9:
            _cap_1.scale_to_fit_height(0.9)
        _cap_1.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 4.0, 6.5)))
        _cap_mobs.append(_cap_1)
        _ptr_1 = VGroup().set_z_index(19)
        _ptr_1.add_updater(lambda m: _cap_point_update(m, _cap_1, lambda: pen, 4.0, 6.5))
        _cap_mobs.append(_ptr_1)
        _cap_2 = Text('The wiggles at the corners never vanish', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_2.width > 13.4:
            _cap_2.scale_to_fit_width(13.4)
        if _cap_2.height > 0.9:
            _cap_2.scale_to_fit_height(0.9)
        _cap_2.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 6.7, 9.2)))
        _cap_mobs.append(_cap_2)
        _ptr_2 = VGroup().set_z_index(19)
        _ptr_2.add_updater(lambda m: _cap_point_update(m, _cap_2, lambda: wave_dot, 6.7, 9.2))
        _cap_mobs.append(_ptr_2)
        self.add(*_cap_mobs)

        harmonics = [1, 3, 5, 7, 9]
        amps = [4.0 / (math.pi * k) for k in harmonics]
        center = np.array([-3.6, 0.0, 0.0])

        title = Text('Build intuition for Fourier series by adding sine harmonics.').scale(0.46).to_edge(UP)

        def chain(tt):
            group = VGroup()
            p = center.copy()
            for k, a in zip(harmonics, amps):
                ang = k * tt
                nxt = p + a * np.array([math.cos(ang), math.sin(ang), 0.0])
                group.add(Circle(radius=a, color=GREY_B, stroke_width=1.5, stroke_opacity=0.35).move_to(p))
                group.add(Line(p, nxt, color=YELLOW, stroke_width=2.5))
                p = nxt
            return group, p

        def tip(tt):
            return chain(tt)[1]

        def wave_value(tt):
            return float(sum(a * math.sin(k * tt) for k, a in zip(harmonics, amps)))

        axes = Axes(
            x_range=[0.0, 2.0 * math.pi, math.pi / 2.0],
            y_range=[-1.4, 1.4, 0.5],
            x_length=5.5, y_length=3.2,
            axis_config={"include_tip": False, "stroke_opacity": 0.5},
        ).shift(RIGHT * 2.4)
        target = axes.plot(lambda x: sum(a * math.sin(k * x) for k, a in zip(harmonics, amps)),
                           x_range=[0.0, 2.0 * math.pi], color=BLUE_C)

        t = ValueTracker(0.0)
        phasors = always_redraw(lambda: chain(t.get_value())[0])
        pen = always_redraw(lambda: Dot(tip(t.get_value()), color=YELLOW, radius=0.05))
        drawing = TracedPath(lambda: tip(t.get_value()), stroke_color=TEAL, stroke_width=2.5)
        wave_dot = always_redraw(lambda: Dot(
            axes.c2p(t.get_value(), wave_value(t.get_value())), color=YELLOW, radius=0.06))
        link = always_redraw(lambda: DashedLine(
            tip(t.get_value()),
            axes.c2p(t.get_value(), wave_value(t.get_value())),
            color=GREY_B, stroke_width=1.5, dash_length=0.08))

        self.play(FadeIn(title), Create(axes), run_time=1.0)
        self.add(phasors, drawing, pen, link, wave_dot)
        self.play(t.animate.set_value(2.0 * math.pi), Create(target),
                  run_time=8.0, rate_func=linear)
        self.wait(0.5)

        # AetherLab explanation layer: keep the animation as a thumbnail and explain beside it.
        self.remove(_clock, _cap_band, *_cap_mobs)
        for _m in self.mobjects:
            _m.clear_updaters()
        # play() adds animated ValueTrackers to the scene; each is a point at x = its
        # value, which would stretch the stage's bounding box and shrink the thumbnail.
        self.remove(*[_m for _m in self.mobjects if isinstance(_m, ValueTracker)])
        _stage = Group(*self.mobjects)
        if len(_stage) and _stage.width > 0.1:
            _s = min(4.8 / _stage.width, 3.3 / max(_stage.height, 0.1), 1.0)
            self.play(_stage.animate.scale(_s).to_corner(UL, buff=0.45), run_time=1.0)
        _thumb_box = SurroundingRectangle(_stage, color=GREY_B, buff=0.12, stroke_width=1.5, corner_radius=0.08)
        _eq = Text('f(x) = (4/π)·Σ sin(n·x)/n, n = 1,\n3, 5, ...', font_size=24, color=WHITE)
        _eq_w = max(_thumb_box.width, 3.2)
        if _eq.width > _eq_w:
            _eq.scale_to_fit_width(_eq_w)
        _eq.next_to(_thumb_box, DOWN, buff=0.35).align_to(_thumb_box, LEFT)
        self.play(Create(_thumb_box), FadeIn(_eq), run_time=0.6)
        _left = VGroup(_thumb_box, _eq)
        _side_w = max(4.0, 6.9 - _left.get_right()[0] - 0.55)

        # Beat A: the prediction's answer, then the misconception confronted.
        _pa_head = Text('The answer', font_size=30, weight=BOLD, color=YELLOW)
        _pa_text = Text('No. It stays near 9% of the jump; more\ncircles only make it narrower (the Gibbs\nphenomenon).', font_size=24, color=WHITE)
        _mis_head = Text('Common idea', font_size=24, weight=BOLD, color=RED_B)
        _mis_wrong = Text('With enough terms, a Fourier series matches\nevery point exactly.', font_size=24, color=RED_A)
        _mis_fix_head = Text('What actually happens', font_size=24, weight=BOLD, color=GREEN_B)
        _mis_fix = Text('At a jump the overshoot never shrinks below\nabout 9%; it only gets narrower.', font_size=24, color=GREEN_A)
        _beat_a = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong, _mis_fix_head, _mis_fix).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        if _beat_a.width > _side_w:
            _beat_a.scale_to_fit_width(_side_w)
        if _beat_a.height > 6.6:
            _beat_a.scale_to_fit_height(6.6)
        _beat_a.next_to(_left, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        _first = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong)
        self.play(FadeIn(_first, shift=0.2 * LEFT), run_time=0.8)
        self.wait(1.2)
        _cross = Cross(_mis_wrong, stroke_color=RED, stroke_width=4)
        self.play(Create(_cross), FadeIn(_mis_fix_head), FadeIn(_mis_fix), run_time=0.8)
        self.wait(1.8)
        self.play(FadeOut(_beat_a), FadeOut(_cross), run_time=0.5)

        # Beat B: the key numbers and the takeaway, beside the thumbnail.
        _head = Text('What the animation shows', font_size=30, weight=BOLD, color=YELLOW)
        _facts = VGroup(Text('5 odd harmonics are used: n = 1, 3, 5, 7, 9', font_size=23, color=GREY_A), Text('Circle n has radius 4/(π·n): higher\nharmonics add finer detail', font_size=23, color=GREY_A), Text('Near the jumps the sum overshoots by about\n9% (the Gibbs phenomenon)', font_size=23, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.26)
        _key = Text('Enough rotating circles can draw any\nrepeating shape. A square wave needs only\nthe odd harmonics.', font_size=24, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.2, corner_radius=0.12)
        _beat_b = VGroup(_head, _facts, VGroup(_key, _key_box)).arrange(DOWN, aligned_edge=LEFT, buff=0.34)
        if _beat_b.width > _side_w:
            _beat_b.scale_to_fit_width(_side_w)
        if _beat_b.height > 6.6:
            _beat_b.scale_to_fit_height(6.6)
        _beat_b.next_to(_left, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        self.play(FadeIn(_head, shift=0.2 * DOWN), run_time=0.8)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=3.3)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.0)
        self.wait(1.8)
