"""Generated by AetherLab (deterministic oscillator template)."""

import math

import numpy as np

from manim import *

config.background_color = "#0A0A0F"


class AetherLabScene(Scene):
    def construct(self):
        TXT = '#F8FAFC'
        title = Text('The work done by a spring is the signed area under its linear F–x curv', color=TXT).scale(0.5)
        title.to_edge(UP)
        summary = Text("The work done by a spring is the signed area under its linear F–x curve. Hooke's law F = −kx integrates to...", color=TXT).scale(0.3)
        summary.next_to(title, DOWN, buff=0.15)
        steps = [
            "Spring force obeys Hooke's law: F(x) = −kx, a straight line through the origin...",
            'Work is the path integral of force along x: W = ∫_{x_i}^{x_f} F(x) dx.',
            'Substitute F = −kx and integrate: W = −½k(x_f² − x_i²). With x_i = 0, W(x) = −½...'
        ]
        rows = VGroup(*[Text(f"{i}. {s}", color=TXT).scale(0.24) for i, s in enumerate(steps, 1)])
        rows.arrange(DOWN, aligned_edge=LEFT, buff=0.12)
        rows.next_to(summary, DOWN, buff=0.2)
        self.add(title, summary, rows)

        axes = Axes(x_range=[-3, 3, 1], y_range=[-2, 2, 1]).scale(0.5)
        axes.to_edge(DOWN)
        damping = ValueTracker(0.15)
        stiffness = ValueTracker(1.0)

        def curve_fn():
            d = damping.get_value()
            k = stiffness.get_value()
            fn = lambda x: math.exp(-d * (x + 3)) * math.sin(k * x * 2)
            if hasattr(axes, "plot"):
                return axes.plot(fn, color='#06B6D4')
            return axes.get_graph(fn, color='#06B6D4')

        curve = always_redraw(curve_fn)
        self.add(axes)
        self.play(Create(curve_fn()), run_time=1.50)
        self.add(curve)
        self.play(damping.animate.set_value(0.5499999999999999), run_time=2.50,
                  rate_func=there_and_back)
        self.wait(1)
