"""Generated by AetherLab - scenario: two waves meet."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Two waves meet', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('A·sin(kx - ωt) + A·sin(kx + ωt) = 2A·sin(kx)·cos(ωt)', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: a right-moving wave (top) and a left-moving\nwave (middle) add up to the bottom row.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.0)
        self.wait(1.8)
        self.play(FadeOut(_intro), run_time=0.5)

        n = 3
        x0, length = -5.4, 10.8
        k = n * PI / length
        amp = 0.55
        rows = {"right": 2.05, "left": 0.35, "sum": -1.95}
        phase = ValueTracker(0.0)
        xs = np.linspace(x0, x0 + length, 220)

        def curve(kind, y0, color):
            def draw():
                w = phase.get_value()
                u = k * (xs - x0)
                if kind == "right":
                    ys = amp * np.sin(u - w)
                elif kind == "left":
                    ys = amp * np.sin(u + w)
                else:
                    ys = amp * (np.sin(u - w) + np.sin(u + w))
                line = VMobject(color=color, stroke_width=4)
                line.set_points_as_corners([np.array([x, y0 + y, 0.0]) for x, y in zip(xs, ys)])
                return line
            return always_redraw(draw)

        title = Text("Two waves meet", font_size=34, color=YELLOW).to_edge(UP, buff=0.25)
        axes = VGroup(*[
            Line([x0, y, 0], [x0 + length, y, 0], color=GREY_D, stroke_width=1.5)
            for y in rows.values()
        ])
        right = curve("right", rows["right"], BLUE)
        left = curve("left", rows["left"], RED)
        total = curve("sum", rows["sum"], TEAL)
        tag_r = Text("travels right", font_size=24, color=BLUE).move_to([5.3, rows["right"] + 0.85, 0])
        tag_l = Text("travels left", font_size=24, color=RED).move_to([5.3, rows["left"] + 0.85, 0])
        tag_s = Text("sum: stands still", font_size=24, color=TEAL).move_to([5.0, rows["sum"] + 1.35, 0])
        arrow_r = Arrow([3.9, rows["right"] + 0.85, 0], [4.5, rows["right"] + 0.85, 0], color=BLUE, buff=0)
        arrow_l = Arrow([4.5, rows["left"] + 0.85, 0], [3.9, rows["left"] + 0.85, 0], color=RED, buff=0)
        plus = Text("+", font_size=40, color=GREY_B).move_to([x0 - 0.45, (rows["right"] + rows["left"]) / 2, 0])
        equals = Text("=", font_size=40, color=GREY_B).move_to([x0 - 0.45, (rows["left"] + rows["sum"]) / 2, 0])

        node_xs = [x0 + length * j / n for j in range(n + 1)]
        nodes = VGroup(*[
            DashedLine([x, rows["right"] + 0.75, 0], [x, rows["sum"] - 1.25, 0],
                       color=GREY_B, stroke_width=1.5, dash_length=0.1)
            for x in node_xs
        ])
        node_dots = VGroup(*[Dot([x, rows["sum"], 0], color=RED, radius=0.08) for x in node_xs])
        node_tag = Text("nodes: the two waves always cancel here", font_size=24,
                        color=GREY_A).move_to([0, rows["sum"] - 1.55, 0])

        self.play(FadeIn(title), Create(axes), run_time=0.8)
        # The right-moving wave on its own, then the left-moving one.
        self.play(FadeIn(right), FadeIn(tag_r), GrowArrow(arrow_r), run_time=0.6)
        self.play(phase.animate.set_value(PI), run_time=1.6, rate_func=linear)
        self.play(FadeIn(left), FadeIn(tag_l), GrowArrow(arrow_l), FadeIn(plus), run_time=0.6)
        self.play(phase.animate.set_value(2 * PI), run_time=1.6, rate_func=linear)
        # Their sum, which does not travel.
        self.play(FadeIn(total), FadeIn(tag_s), FadeIn(equals), run_time=0.6)
        self.play(phase.animate.set_value(4 * PI), run_time=3.2, rate_func=linear)
        self.play(Create(nodes), GrowFromCenter(node_dots), FadeIn(node_tag), run_time=1.0)
        self.play(phase.animate.set_value(6 * PI + PI / 2), run_time=3.6, rate_func=linear)
        # Freeze at the instant the waves cancel everywhere: the sum is flat.
        flat = Text("right now they cancel everywhere: the string is flat, yet still moving",
                    font_size=24, color=YELLOW_A).move_to(node_tag)
        self.play(Indicate(total, color=YELLOW), FadeOut(node_tag), FadeIn(flat), run_time=1.0)
        self.wait(1.2)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in self.mobjects:
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(*self.mobjects), run_time=0.8)
        _head = Text('What the animation shows', font_size=34, weight=BOLD, color=YELLOW)
        _eq = Text('A·sin(kx - ωt) + A·sin(kx + ωt) = 2A·sin(kx)·cos(ωt)', font_size=28, color=WHITE)
        _facts = VGroup(Text('Mode n = 3: 4 nodes (including the ends), where the two waves always\ncancel', font_size=25, color=GREY_A), Text('Wavelength λ = 2L/n = 0.67·L', font_size=25, color=GREY_A), Text('Once per half cycle the two waves cancel everywhere and the string is\nflat', font_size=25, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _key = Text('A standing wave is two equal waves travelling in opposite directions.\nNeither stops; their sum just stops travelling.', font_size=27, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.42)
        if _card.width > 12.4:
            _card.scale_to_fit_width(12.4)
        if _card.height > 7.0:
            _card.scale_to_fit_height(7.0)
        self.play(FadeIn(_head, shift=0.2 * DOWN), FadeIn(_eq), run_time=1.2)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=4.2)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.2)
        self.wait(3.5)
