"""Generated by AetherLab - quantum wavepacket (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        title = Text('Show double-slit interference and the resulting fringe patt…').scale(0.46).to_edge(UP)

        axes = Axes(
            x_range=[-4.0, 4.0, 1.0], y_range=[0.0, 3.2, 1.0],
            x_length=10.0, y_length=5.0,
            axis_config={"include_tip": False, "stroke_opacity": 0.45},
        ).to_edge(DOWN)
        x_label = axes.get_x_axis_label(Text("x").scale(0.4))

        # Harmonic potential well V(x) = 0.5 * k * x^2 (scaled to fit).
        k = 0.32
        well = axes.plot(lambda x: 0.5 * k * x * x, x_range=[-3.6, 3.6], color=BLUE_D)
        well.set_stroke(opacity=0.7)

        # A few quantized energy levels as faint horizontal lines.
        levels = VGroup()
        for e in (0.6, 1.4, 2.4):
            xr = np.sqrt(max(2.0 * e / k, 0.0))
            levels.add(DashedLine(axes.c2p(-xr, e), axes.c2p(xr, e),
                                  color=GREY_B, stroke_width=1.5, stroke_opacity=0.5))

        # Coherent-state probability density: a Gaussian whose centre oscillates.
        amp = 2.6
        omega = 1.0
        sigma = 0.6
        height = 2.4
        grid = np.linspace(-3.8, 3.8, 64)
        t = ValueTracker(0.0)

        def packet():
            x0 = amp * np.cos(omega * t.get_value())
            tops = [axes.c2p(x, height * np.exp(-((x - x0) ** 2) / (2 * sigma ** 2)))
                    for x in grid]
            base = [axes.c2p(x, 0.0) for x in grid[::-1]]
            poly = Polygon(*tops, *base, color=TEAL,
                           fill_color=TEAL, fill_opacity=0.35, stroke_width=2.5)
            return poly

        density = always_redraw(packet)
        psi_tag = Text("|psi(x,t)|^2", color=TEAL).scale(0.34).to_corner(UR, buff=0.7)

        self.play(FadeIn(title), Create(axes), FadeIn(x_label), run_time=1.0)
        self.play(Create(well), LaggedStart(*[Create(l) for l in levels], lag_ratio=0.2),
                  run_time=1.4)
        self.add(density)
        self.play(FadeIn(psi_tag), run_time=0.5)
        self.play(t.animate.set_value(2.0 * PI), run_time=6.5, rate_func=linear)
        self.wait(0.4)
