"""Generated by AetherLab - Fourier epicycles (curated component)."""

import math

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        harmonics = [1, 3, 5, 7, 9]
        amps = [4.0 / (math.pi * k) for k in harmonics]
        center = np.array([-3.6, 0.0, 0.0])

        title = Text('Build intuition for Fourier series by adding sine harmonics.').scale(0.46).to_edge(UP)

        def chain(tt):
            group = VGroup()
            p = center.copy()
            for k, a in zip(harmonics, amps):
                ang = k * tt
                nxt = p + a * np.array([math.cos(ang), math.sin(ang), 0.0])
                group.add(Circle(radius=a, color=GREY_B, stroke_width=1.5, stroke_opacity=0.35).move_to(p))
                group.add(Line(p, nxt, color=YELLOW, stroke_width=2.5))
                p = nxt
            return group, p

        def tip(tt):
            return chain(tt)[1]

        def wave_value(tt):
            return float(sum(a * math.sin(k * tt) for k, a in zip(harmonics, amps)))

        axes = Axes(
            x_range=[0.0, 2.0 * math.pi, math.pi / 2.0],
            y_range=[-1.4, 1.4, 0.5],
            x_length=5.5, y_length=3.2,
            axis_config={"include_tip": False, "stroke_opacity": 0.5},
        ).shift(RIGHT * 2.4)
        target = axes.plot(lambda x: sum(a * math.sin(k * x) for k, a in zip(harmonics, amps)),
                           x_range=[0.0, 2.0 * math.pi], color=BLUE_C)

        t = ValueTracker(0.0)
        phasors = always_redraw(lambda: chain(t.get_value())[0])
        pen = always_redraw(lambda: Dot(tip(t.get_value()), color=YELLOW, radius=0.05))
        drawing = TracedPath(lambda: tip(t.get_value()), stroke_color=TEAL, stroke_width=2.5)
        wave_dot = always_redraw(lambda: Dot(
            axes.c2p(t.get_value(), wave_value(t.get_value())), color=YELLOW, radius=0.06))
        link = always_redraw(lambda: DashedLine(
            tip(t.get_value()),
            axes.c2p(t.get_value(), wave_value(t.get_value())),
            color=GREY_B, stroke_width=1.5, dash_length=0.08))

        self.play(FadeIn(title), Create(axes), run_time=1.0)
        self.add(phasors, drawing, pen, link, wave_dot)
        self.play(t.animate.set_value(2.0 * math.pi), Create(target),
                  run_time=8.0, rate_func=linear)
        self.wait(0.5)
