"""Generated by AetherLab - scenario: photon by photon."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # =====================================================================
        # Color palette
        # =====================================================================
        C_BG      = "#0B1020"
        C_TITLE   = "#FFD93B"
        C_SLIT    = "#D7DBE6"
        C_SCREEN  = "#AAB2C0"
        C_AXIS    = "#5A627A"
        C_TICK    = "#8A93AE"
        C_PHOTON  = "#FFE066"
        C_GLOW    = "#FFB347"
        C_FRINGE  = "#42E0D0"
        C_HUMP    = "#FF7A6B"
        C_BAND    = "#FFD93B"
        C_DIM     = "#9AA3B8"
        C_SHUT    = "#D94436"
        C_SHUTS   = "#7A1F1F"

        self.camera.background_color = C_BG

        # =====================================================================
        # Geometry & experiment parameters
        #   slit separation  d = 2*half_gap = 2.0
        #   wavelength       lam = 1.0
        #   bright bands at  d*sin(theta) = m*lam  ->  sin(theta) = m/2
        #   Screen height = 6  -> screen_y = 3 (tall), y_mid = 0
        #   bright band spacing in y ~ 1.0 at small-angle approx
        # =====================================================================
        half_gap    = 1.0
        d           = 2 * half_gap
        lam         = 1.0
        source_pt   = np.array([-6.0, 0.0, 0.0])
        barrier_x   = -2.9
        screen_x    = 2.7
        screen_top  =  3.0
        screen_bot  = -3.0
        bins        = 21
        edges       = np.linspace(-2.1, 2.1, bins + 1)
        max_y       = (edges[-1] + edges[0]) / 2.0  # = 0

        # =====================================================================
        # Persistent frame: title bar, apparatus, labeled axes
        # =====================================================================
        title = Text("Photon by photon", font_size=34, weight=BOLD,
                     color=C_TITLE).to_edge(UP, buff=0.25)

        # Source (single photon emitter)
        source = Dot(source_pt, color=C_PHOTON, radius=0.16)
        glow   = Dot(source_pt, color=C_GLOW, radius=0.45).set_opacity(0.35)
        source_lbl = Text("source", font_size=20, color=C_DIM).next_to(
            source, DOWN, buff=0.18)

        # Slit barrier with two labeled openings
        slit_w      = 0.28
        top_y       = max_y + half_gap
        bot_y       = max_y - half_gap
        barrier = VGroup(
            Line([barrier_x, screen_top,        0], [barrier_x, top_y + slit_w/2, 0],
                 color=C_SLIT, stroke_width=9),
            Line([barrier_x, top_y - slit_w/2, 0], [barrier_x, bot_y + slit_w/2, 0],
                 color=C_SLIT, stroke_width=9),
            Line([barrier_x, bot_y - slit_w/2, 0], [barrier_x, screen_bot,        0],
                 color=C_SLIT, stroke_width=9),
        )
        slit_top_lbl = Text("slit 1", font_size=18, color=C_DIM).next_to(
            barrier[0].point_from_proportion(0.55), LEFT, buff=0.18)
        slit_bot_lbl = Text("slit 2", font_size=18, color=C_DIM).next_to(
            barrier[2].point_from_proportion(0.45), LEFT, buff=0.18)

        # Detector screen + labeled axis (y is vertical position, like a strip)
        screen   = Line([screen_x, screen_top, 0], [screen_x, screen_bot, 0],
                        color=C_SCREEN, stroke_width=5)
        axis_x   = screen_x + 0.42
        det_axis = Line([axis_x, screen_top, 0], [axis_x, screen_bot, 0],
                        color=C_AXIS, stroke_width=2)

        # Angular axis at the bottom (theta drawn from the barrier)
        theta_arc = Arc(radius=2.2, start_angle=0, angle=PI/4, color=C_AXIS, stroke_width=2)
        theta_arc.move_arc_center_to(np.array([barrier_x, max_y, 0]))
        theta_lbl = MathTex(r"\theta", font_size=30, color=C_DIM).move_to(
            [barrier_x + 2.7, 0.9, 0])
        d_label = MathTex(r"d", font_size=28, color=C_DIM).move_to(
            [barrier_x + 0.45, max_y - half_gap/2, 0])

        # y-axis ticks on the detector (every 1 unit), labeled in screen-y space
        y_ticks = VGroup()
        for y in [-2, -1, 0, 1, 2]:
            y_ticks.add(Line([axis_x - 0.08, y, 0], [axis_x + 0.08, y, 0],
                             color=C_TICK, stroke_width=1.8))
        y_tick_lbls = VGroup(
            Text("+2", font_size=16, color=C_TICK).move_to([axis_x + 0.28,  2, 0]),
            Text("+1", font_size=16, color=C_TICK).move_to([axis_x + 0.28,  1, 0]),
            Text(" 0", font_size=16, color=C_TICK).move_to([axis_x + 0.28,  0, 0]),
            Text("-1", font_size=16, color=C_TICK).move_to([axis_x + 0.28, -1, 0]),
            Text("-2", font_size=16, color=C_TICK).move_to([axis_x + 0.28, -2, 0]),
        )
        y_axis_lbl = MathTex(r"y", font_size=28, color=C_DIM).move_to(
            [axis_x + 0.55, screen_top - 0.55, 0])

        det_axis_lbl = Text("detector", font_size=22, color=C_DIM).next_to(
            screen, UP, buff=0.18)

        # Equation banner (visible from the start, stays through physics acts)
        eq_banner = Text(
            r"Intensity:  I(y) = 2 I\u2080 (1 + cos( 2\u03c0 d sin\u03b8 / \u03bb ))     bright bands where d sin\u03b8 = m \u03bb",
            font_size=22, color=C_DIM,
        ).to_edge(DOWN, buff=0.2)

        apparatus = VGroup(
            glow, source, source_lbl,
            barrier, slit_top_lbl, slit_bot_lbl, d_label,
            screen, det_axis_lbl,
            theta_arc, theta_lbl,
            det_axis, y_ticks, y_tick_lbls, y_axis_lbl,
            title, eq_banner,
        )

        self.play(
            FadeIn(title, shift=0.2*DOWN),
            FadeIn(glow), GrowFromCenter(source),
            LaggedStart(*[Create(m) for m in [barrier, screen, theta_arc, det_axis]],
                        lag_ratio=0.25),
            LaggedStart(*[FadeIn(m) for m in
                          [source_lbl, slit_top_lbl, slit_bot_lbl, d_label,
                           det_axis_lbl, theta_lbl, y_axis_lbl]],
                        lag_ratio=0.12),
            LaggedStart(*[FadeIn(t) for t in y_ticks], lag_ratio=0.06),
            LaggedStart(*[FadeIn(l) for l in y_tick_lbls], lag_ratio=0.06),
            FadeIn(eq_banner),
            run_time=2.0,
        )

        # =====================================================================
        # Photon samples for two-slit (interference) and one-slit (no interference)
        # Both drawn from the analytic forms so labels match
        #   two-slit: P(y) ∝ cos²(pi * d * y / (lam * L)) ; choose L = 4 so d/L=0.5
        #   single : P(y) ∝ sinc²(pi * a * y / (lam * L)) ; use a = 0.6, L = 4
        # =====================================================================
        rng = np.random.default_rng(7)
        n_two = 360
        n_one = 280

        # Two-slit: reject samples from the cos² envelope on [-2.1, 2.1]
        def sample_two(n):
            ys = []
            while len(ys) < n:
                y = rng.uniform(-2.0, 2.0)
                L = 4.0
                p = np.cos(np.pi * d * y / (lam * L))**2
                if rng.random() < p:
                    ys.append(y)
            return np.array(ys)

        def sample_one(n):
            ys = []
            while len(ys) < n:
                y = rng.uniform(-2.0, 2.0)
                L = 4.0
                a = 0.6
                arg = np.pi * a * y / (lam * L)
                p = (np.sinc(arg / np.pi))**2
                if rng.random() < p:
                    ys.append(y)
            return np.array(ys)

        two_hits = sample_two(n_two)
        one_hits = sample_one(n_one)

        # =====================================================================
        # ACT 1 — one photon at a time  (visible single hits, then accumulation)
        # =====================================================================
        act1_lbl = Text("act 1 — one photon at a time",
                        font_size=22, color=C_DIM).next_to(eq_banner, UP, buff=0.18)

        self.play(FadeIn(act1_lbl), run_time=0.4)

        # A handful of slow, very visible photon arrivals
        slow_hits = [two_hits[i] for i in [0, 90, 180, 270, 320]]
        slow_dots = VGroup()
        for y in slow_hits:
            d_ = Dot([screen_x + 0.05, y, 0.0], color=C_PHOTON, radius=0.07)
            slow_dots.add(d_)
        self.add(slow_dots[0])
        self.play(
            Flash(source, color=C_PHOTON, line_length=0.22, flash_radius=0.35,
                  num_lines=10),
            FadeIn(slow_dots[0], scale=6), run_time=0.5,
        )
        for d_ in slow_dots[1:]:
            self.play(
                Flash(source, color=C_PHOTON, line_length=0.22, flash_radius=0.35,
                      num_lines=10),
                FadeIn(d_, scale=6), run_time=0.45,
            )

        # =====================================================================
        # ACCUMULATION — histogram bars build up while dots keep landing
        # =====================================================================
        all_dots = VGroup(*slow_dots)

        def add_dot(group):
            n_show = int(count.get_value())
            extras = n_show - len(group)
            if extras > 0:
                for j in range(extras):
                    idx = len(group)
                    if idx >= len(two_hits):
                        break
                    new = Dot([screen_x + 0.05, two_hits[idx], 0.0],
                              color=C_PHOTON, radius=0.045)
                    group.add(new)

        def make_bars():
            n_show = int(count.get_value())
            ys = two_hits[:max(n_show, 1)]
            counts, _ = np.histogram(ys, bins=edges)
            scale = 1.95 / max(1, counts.max())
            bars = VGroup()
            for c, lo, hi in zip(counts, edges[:-1], edges[1:]):
                h = (hi - lo) * 0.78
                w = max(0.0, c * scale)
                if w > 0.001:
                    bar = Rectangle(width=w, height=h,
                                    fill_color=C_FRINGE, fill_opacity=0.92,
                                    stroke_width=0)
                    bar.move_to([axis_x - 0.55 + w/2,
                                 max_y + (lo + hi)/2, 0])
                    bars.add(bar)
            return bars

        def make_counter():
            n_show = int(count.get_value())
            txt = f"photons: {n_show}" if n_show < 1000 else f"photons: {n_show//10*10}+"
            return Text(txt, font_size=22, color=WHITE).move_to([-4.9, 2.6, 0])

        count = ValueTracker(len(slow_dots))
        all_dots.add_updater(add_dot)
        self.add(all_dots)
        bars     = always_redraw(make_bars)
        tally    = always_redraw(make_counter)
        self.play(FadeIn(bars), FadeIn(tally), run_time=0.6)
        self.play(count.animate.set_value(float(n_two)),
                  run_time=5.5, rate_func=rate_functions.ease_in_quad)

        # Bright-band labels appear on top of the histogram
        band_label_y = [0.0, 1.0, -1.0, 2.0, -2.0]   # m = 0, ±1, ±2
        band_m       = ["m = 0", "m = +1", "m = -1", "m = +2", "m = -2"]
        band_labels  = VGroup()
        m_guides = VGroup()
        for y, m in zip(band_label_y, band_m):
            mtxt = Text(m, font_size=18, color=C_BAND)
            mtxt.move_to([axis_x - 1.6, y, 0])
            band_labels.add(mtxt)
            dotted = DashedLine([screen_x - 0.15, y, 0],
                                [axis_x - 0.25, y, 0],
                                color=C_BAND, stroke_width=1.5, dash_length=0.06)
            m_guides.add(dotted)

        self.play(
            LaggedStart(*[FadeIn(m, shift=0.2*LEFT) for m in band_labels], lag_ratio=0.2),
            LaggedStart(*[Create(d) for d in m_guides], lag_ratio=0.2),
            run_time=1.6,
        )

        # Highlight verdict line for act 1
        verdict1 = Text("bright bands are 1.0 units apart  →  d sinθ = m λ",
                        font_size=22, color=C_FRINGE).move_to([-0.7, -2.4, 0])
        self.play(FadeOut(act1_lbl), FadeIn(verdict1), run_time=0.5)
        self.wait(1.4)

        # =====================================================================
        # ACT 2 — cover one slit; the pattern collapses to a single hump
        # =====================================================================
        all_dots.clear_updaters()
        verdict2_old = verdict1
        self.play(
            FadeOut(all_dots), FadeOut(band_labels), FadeOut(m_guides),
            run_time=0.8,
        )
        bars.clear_updaters()

        act2_lbl = Text("act 2 — cover one slit",
                        font_size=22, color=C_DIM).next_to(eq_banner, UP, buff=0.18)

        # Cover the bottom slit with a red shutter
        shutter = Rectangle(width=0.5, height=slit_w + 0.18,
                            fill_color=C_SHUT, fill_opacity=1.0,
                            stroke_color=C_SHUTS, stroke_width=2)
        shutter.move_to([barrier_x, bot_y, 0])
        self.play(FadeIn(act2_lbl), FadeIn(shutter), run_time=0.5)

        # Re-define bars/tally but driven by one_hits and a different color
        def add_dot1(group):
            n_show = int(count1.get_value())
            extras = n_show - len(group)
            if extras > 0:
                for _ in range(extras):
                    idx = len(group)
                    if idx >= len(one_hits):
                        break
                    new = Dot([screen_x + 0.05, one_hits[idx], 0.0],
                              color=C_PHOTON, radius=0.045)
                    group.add(new)

        def make_bars1():
            n_show = int(count1.get_value())
            ys = one_hits[:max(n_show, 1)]
            counts, _ = np.histogram(ys, bins=edges)
            scale = 1.95 / max(1, counts.max())
            bars_ = VGroup()
            for c, lo, hi in zip(counts, edges[:-1], edges[1:]):
                h = (hi - lo) * 0.78
                w = max(0.0, c * scale)
                if w > 0.001:
                    bar = Rectangle(width=w, height=h,
                                    fill_color=C_HUMP, fill_opacity=0.92,
                                    stroke_width=0)
                    bar.move_to([axis_x - 0.55 + w/2,
                                 max_y + (lo + hi)/2, 0])
                    bars_.add(bar)
            return bars_

        def make_counter1():
            n_show = int(count1.get_value())
            txt = f"photons: {n_show}" if n_show < 1000 else f"photons: {n_show//10*10}+"
            return Text(txt, font_size=22, color=WHITE).move_to([-4.9, 2.6, 0])

        count1 = ValueTracker(0.0)
        dots1 = VGroup()
        dots1.add_updater(add_dot1)
        bars1 = always_redraw(make_bars1)
        tally1 = always_redraw(make_counter1)
        self.add(dots1, bars1, tally1)
        self.play(count1.animate.set_value(float(n_one)),
                  run_time=4.5, rate_func=rate_functions.ease_in_quad)

        # Guide: one broad hump marker at y = 0
        hump_guide = DashedLine([screen_x - 0.15, 0, 0], [axis_x - 0.25, 0, 0],
                                color=C_HUMP, stroke_width=2, dash_length=0.08)
        hump_lbl   = Text("single hump", font_size=18, color=C_HUMP).move_to(
            [axis_x - 1.7, 0.25, 0])

        verdict2 = Text("with one path, the bands vanish — one broad central hump",
                        font_size=22, color=C_HUMP).move_to([-1.6, -2.4, 0])
        self.play(
            FadeOut(act2_lbl),
            Create(hump_guide), FadeIn(hump_lbl),
            FadeIn(verdict2),
            run_time=1.0,
        )
        self.wait(1.4)

        # =====================================================================
        # SYNTHESIS — equation swap, then a short recap card (no naked grid)
        # =====================================================================
        dots1.clear_updaters()
        bars1.clear_updaters()

        new_eq = Text(
            r"Two slits:  I(y) \u221d cos\u00b2(\u03c0 d y / (\u03bb L))     One slit:  I(y) \u221d sinc\u00b2(\u03c0 a y / (\u03bb L))",
            font_size=22, color=C_DIM,
        ).move_to(eq_banner.get_center())

        self.play(
            Transform(eq_banner, new_eq),
            FadeOut(verdict2_old),
            run_time=0.8,
        )

        # Recap card slides in next to the apparatus (kept compact, no clear())
        rec_title = Text("Why this matters", font_size=30, weight=BOLD, color=C_TITLE)
        rec_lines = VGroup(
            Text("• each photon lands at one spot — never a wave",
                 font_size=22, color=WHITE),
            Text("• a single photon's wave still goes through both slits,",
                 font_size=22, color=WHITE),
            Text("  and interferes with itself into bands",
                 font_size=22, color=WHITE),
            Text("• block one slit → interference bands collapse to a hump",
                 font_size=22, color=WHITE),
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.22)

        rec_box = SurroundingRectangle(
            VGroup(rec_title, rec_lines), color=C_FRINGE,
            buff=0.28, corner_radius=0.12,
        )
        rec_card = VGroup(rec_box, rec_title, rec_lines)
        rec_title.next_to(rec_box.get_top(), DOWN, buff=0.32)
        rec_lines.next_to(rec_title, DOWN, buff=0.25).align_to(rec_title, LEFT)
        rec_card.move_to([-3.2, -0.6, 0])
        if rec_card.height > 5.5:
            rec_card.scale_to_fit_height(5.5)
        if rec_card.width > 6.6:
            rec_card.scale_to_fit_width(6.6)

        # Move a *copy* of the apparatus aside; do NOT clear the stage.
        apparatus_target = VGroup(
            barrier, screen, det_axis, y_ticks, y_tick_lbls, y_axis_lbl,
            source, glow, source_lbl, slit_top_lbl, slit_bot_lbl, d_label,
            theta_arc, theta_lbl,
            bars1, hump_guide, hump_lbl, dots1,
            title, eq_banner, tally1,
        )
        self.play(
            FadeIn(rec_card, shift=0.3 * RIGHT),
            run_time=1.0,
        )
        self.wait(0.6)

        # Closing flourish — re-emphasize the m labels with a final Hold
        closing = Text(
            "Bands need two open paths — even one photon at a time.",
            font_size=24, color=C_BAND,
        ).to_edge(DOWN, buff=0.25)
        self.play(FadeIn(closing, shift=0.3 * UP), run_time=0.7)
        self.wait(0.8)

        # END frame: histogram still visibly redrawn between last two frames
        # Slight pulse on the m=0 band so the last samples differ
        m0_band = bars1  # bars1 is the hump histogram (single-slit)
        # Instead, pulse the static dashed hump guide to keep a living ending
        self.play(
            hump_guide.animate.set_stroke(width=4),
            hump_lbl.animate.scale(1.15),
            rate_func=rate_functions.there_and_back,
            run_time=1.0,
        )
        self.wait(0.6)