"""Generated by AetherLab - nonlinear pendulum (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('The pendulum and its period', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text("θ'' = -(g/L)·sin θ - 2γ·θ'", font_size=30, color=WHITE)
        _intro_watch = Text('Watch: the bob swings on the left while its angle θ(t)\nis drawn on the right.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.2)
        self.wait(3.4)
        self.play(FadeOut(_intro), run_time=0.6)

        ts = [0.0, 0.07547, 0.15094, 0.22642, 0.30189, 0.37736, 0.45283, 0.5283, 0.60377, 0.67925, 0.75472, 0.83019, 0.90566, 0.98113, 1.0566, 1.13208, 1.20755, 1.28302, 1.35849, 1.43396, 1.50943, 1.58491, 1.66038, 1.73585, 1.81132, 1.88679, 1.96226, 2.03774, 2.11321, 2.18868, 2.26415, 2.33962, 2.41509, 2.49057, 2.56604, 2.64151, 2.71698, 2.79245, 2.86792, 2.9434, 3.01887, 3.09434, 3.16981, 3.24528, 3.32075, 3.39623, 3.4717, 3.54717, 3.62264, 3.69811, 3.77358, 3.84906, 3.92453, 4.0, 4.07547, 4.15094, 4.22642, 4.30189, 4.37736, 4.45283, 4.5283, 4.60377, 4.67925, 4.75472, 4.83019, 4.90566, 4.98113, 5.0566, 5.13208, 5.20755, 5.28302, 5.35849, 5.43396, 5.50943, 5.58491, 5.66038, 5.73585, 5.81132, 5.88679, 5.96226, 6.03774, 6.11321, 6.18868, 6.26415, 6.33962, 6.41509, 6.49057, 6.56604, 6.64151, 6.71698, 6.79245, 6.86792, 6.9434, 7.01887, 7.09434, 7.16981, 7.24528, 7.32075, 7.39623, 7.4717, 7.54717, 7.62264, 7.69811, 7.77358, 7.84906, 7.92453, 8.0, 8.07547, 8.15094, 8.22642, 8.30189, 8.37736, 8.45283, 8.5283, 8.60377, 8.67925, 8.75472, 8.83019, 8.90566, 8.98113, 9.0566, 9.13208, 9.20755, 9.28302, 9.35849, 9.43396, 9.50943, 9.58491, 9.66038, 9.73585, 9.81132, 9.88679, 9.96226, 10.03774, 10.11321, 10.18868, 10.26415, 10.33962, 10.41509, 10.49057, 10.56604, 10.64151, 10.71698, 10.79245, 10.86792, 10.9434, 11.01887, 11.09434, 11.16981, 11.24528, 11.32075, 11.39623, 11.4717, 11.54717, 11.62264, 11.69811, 11.77358, 11.84906, 11.92453, 12.0]
        ths = [1.0, 0.97669, 0.90804, 0.79713, 0.64878, 0.46983, 0.26921, 0.05757, -0.15342, -0.35223, -0.52851, -0.67388, -0.78225, -0.8498, -0.87468, -0.85675, -0.79742, -0.69969, -0.56822, -0.40947, -0.23168, -0.04446, 0.14185, 0.31704, 0.47193, 0.59902, 0.69276, 0.74959, 0.76781, 0.74737, 0.68979, 0.59814, 0.47711, 0.33297, 0.17343, 0.00726, -0.15632, -0.30841, -0.44106, -0.54781, -0.62395, -0.6665, -0.67417, -0.64727, -0.58759, -0.49841, -0.3845, -0.25197, -0.10811, 0.03911, 0.18154, 0.31147, 0.4222, 0.50836, 0.56615, 0.59331, 0.58915, 0.55441, 0.49127, 0.40326, 0.29521, 0.17307, 0.04365, -0.08585, -0.20831, -0.31718, -0.40691, -0.47323, -0.51322, -0.52543, -0.50975, -0.46744, -0.40105, -0.31434, -0.21215, -0.1002, 0.01525, 0.12778, 0.23128, 0.3203, 0.39036, 0.4382, 0.46178, 0.46038, 0.43449, 0.38587, 0.31737, 0.2329, 0.13724, 0.03576, -0.06587, -0.16205, -0.24761, -0.31814, -0.37016, -0.4013, -0.41035, -0.39724, -0.36303, -0.30987, -0.24085, -0.15993, -0.07168, 0.01892, 0.10685, 0.18733, 0.25611, 0.30969, 0.34551, 0.36202, 0.3587, 0.33609, 0.2957, 0.23998, 0.17216, 0.09612, 0.01615, -0.06326, -0.13777, -0.20338, -0.25668, -0.29503, -0.31666, -0.32074, -0.30736, -0.27754, -0.23316, -0.17684, -0.11184, -0.04185, 0.02918, 0.09733, 0.15891, 0.21065, 0.24995, 0.27491, 0.28445, 0.27835, 0.25722, 0.22244, 0.17613, 0.12099, 0.06019, -0.00283, -0.06457, -0.12164, -0.171, -0.21009, -0.23699, -0.25047, -0.25004, -0.23598, -0.20928, -0.17161, -0.1252, -0.07275, -0.01723, 0.03824, 0.0906, 0.13705]
        rod_len = 2.0
        pivot = np.array([-3.3, 1.4, 0.0])

        title = Text('Explain the small-angle pendulum and its period dependence.').scale(0.5).to_edge(UP)

        t_tracker = ValueTracker(float(ts[0]))

        def theta_now():
            return float(np.interp(t_tracker.get_value(), ts, ths))

        def bob_point():
            th = theta_now()
            return pivot + rod_len * np.array([np.sin(th), -np.cos(th), 0.0])

        anchor = Dot(pivot, color=GREY_B, radius=0.05)
        rod = always_redraw(lambda: Line(pivot, bob_point(), color=GREY_A, stroke_width=3))
        bob = always_redraw(lambda: Dot(bob_point(), color=YELLOW, radius=0.16))
        trail = TracedPath(bob_point, stroke_color=TEAL, stroke_width=2.5, dissipating_time=1.6)

        # theta(t) read-out on the right, drawn in sync with the swing.
        axes = Axes(
            x_range=[float(ts[0]), float(ts[-1]), (float(ts[-1]) - float(ts[0])) / 4.0],
            y_range=[-max(abs(min(ths)), abs(max(ths))) * 1.2 - 1e-6,
                     max(abs(min(ths)), abs(max(ths))) * 1.2 + 1e-6,
                     max(abs(min(ths)), abs(max(ths))) / 2.0 + 1e-6],
            x_length=5.0, y_length=3.0,
            axis_config={"include_tip": False, "stroke_opacity": 0.5},
        ).to_corner(DR, buff=0.6)
        y_label = axes.get_y_axis_label(Text("theta").scale(0.35))
        trace_pts = [axes.coords_to_point(t, th) for t, th in zip(ts, ths)]
        trace = VMobject(color=TEAL, stroke_width=3)
        trace.set_points_smoothly(trace_pts)
        readout = always_redraw(lambda: Dot(
            axes.coords_to_point(t_tracker.get_value(), theta_now()),
            color=YELLOW, radius=0.06))

        self.play(FadeIn(title), Create(axes), FadeIn(y_label), run_time=1.0)
        self.add(anchor, rod, bob, trail)
        self.play(GrowFromCenter(bob), run_time=0.5)
        self.add(readout)
        self.play(
            t_tracker.animate.set_value(float(ts[-1])),
            Create(trace),
            run_time=6.0, rate_func=linear,
        )
        self.wait(0.5)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in self.mobjects:
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(*self.mobjects), run_time=0.8)
        _head = Text('What the animation shows', font_size=34, weight=BOLD, color=YELLOW)
        _eq = Text("θ'' = -(g/L)·sin θ - 2γ·θ'", font_size=28, color=WHITE)
        _facts = VGroup(Text('Released from 57 degrees, with L = 1.00 m and g = 9.81 m/s²', font_size=25, color=GREY_A), Text('Small-angle formula: T = 2π·√(L/g) = 2.01 s', font_size=25, color=GREY_A), Text('First swing measured from this simulation: 2.10 s', font_size=25, color=GREY_A), Text('Friction shrinks the swing to about 16 degrees by t = 12 s', font_size=25, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _key = Text('The period depends on L and g, not on the mass. Wide swings take\nlonger than the small-angle formula predicts.', font_size=27, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.42)
        if _card.width > 12.4:
            _card.scale_to_fit_width(12.4)
        if _card.height > 7.0:
            _card.scale_to_fit_height(7.0)
        self.play(FadeIn(_head, shift=0.2 * DOWN), FadeIn(_eq), run_time=1.2)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=5.6)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.2)
        self.wait(8.0)
