"""Generated by AetherLab - nonlinear pendulum (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('The pendulum and its period', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text("θ'' = -(g/L)·sin θ - 2γ·θ'", font_size=30, color=WHITE)
        _intro_watch = Text('Watch: the bob swings on the left while its angle θ(t)\nis drawn on the right.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.0)
        self.wait(1.8)
        self.play(FadeOut(_intro), run_time=0.5)

        # AetherLab explanation layer: predict before the reveal.
        _pq_head = Text('Predict first', font_size=34, weight=BOLD, color=YELLOW)
        _pq_text = Text('Make the bob twice as heavy. Does the swing get\nfaster, slower, or stay the same?', font_size=30, color=WHITE)
        _pq_hint = Text('Decide before you watch.', font_size=24, color=GREY_B)
        _pq_bar = Line(3 * LEFT, 3 * RIGHT, color=YELLOW, stroke_width=6)
        _pq_card = VGroup(_pq_head, _pq_text, _pq_hint, _pq_bar).arrange(DOWN, buff=0.45)
        if _pq_card.width > 12.4:
            _pq_card.scale_to_fit_width(12.4)
        if _pq_card.height > 7.0:
            _pq_card.scale_to_fit_height(7.0)
        self.play(FadeIn(_pq_card, shift=0.2 * UP), run_time=0.8)
        self.play(_pq_bar.animate.scale(0.01, about_edge=LEFT), run_time=2.5, rate_func=linear)
        self.play(FadeOut(_pq_card), run_time=0.5)

        # AetherLab explanation layer: timed captions during the animation, with a
        # highlight ring and pointer on the object each caption describes.
        _clock = ValueTracker(0.0)
        _clock.add_updater(lambda m, dt: m.increment_value(dt))
        self.add(_clock)

        def _cap_alpha(t, a, b):
            return max(0.0, min(1.0, (t - a) / 0.35, (b - t) / 0.35))

        def _cap_pointer(cap, target, alpha):
            end = target.get_center()
            ring = Circle(radius=0.32, color=YELLOW_A, stroke_width=3).move_to(end)
            ring.set_stroke(opacity=alpha)
            start = cap.get_bottom() + 0.12 * DOWN
            if np.linalg.norm(end - start) < 0.9:
                return VGroup(ring).set_z_index(19)
            line = DashedLine(start, end, buff=0.36, color=YELLOW_A, stroke_width=2)
            line.set_stroke(opacity=0.8 * alpha)
            return VGroup(line, ring).set_z_index(19)

        def _cap_point_update(m, cap, target_fn, a, b):
            # The target is looked up lazily: it is only created by the
            # animation below, after this setup code has run.
            alpha = _cap_alpha(_clock.get_value(), a, b)
            if alpha <= 0:
                m.set_stroke(opacity=0)
                return
            try:
                target = target_fn()
            except NameError:
                return
            # Refresh the target first; otherwise the ring trails a moving
            # object by one frame (this updater can run before the target's).
            target.update(0)
            m.become(_cap_pointer(cap, target, alpha))

        _cap_band = Rectangle(width=14.6, height=1.0, stroke_width=0, fill_color=BLACK, fill_opacity=0.0).to_edge(UP, buff=0).set_z_index(20)
        _cap_band.add_updater(lambda m: m.set_fill(BLACK, opacity=_cap_alpha(_clock.get_value(), 1.8, 7.7)))
        self.add(_cap_band)
        _cap_mobs = []
        _cap_0 = Text('Gravity pulls the bob back toward the bottom', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_0.width > 13.4:
            _cap_0.scale_to_fit_width(13.4)
        if _cap_0.height > 0.9:
            _cap_0.scale_to_fit_height(0.9)
        _cap_0.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 1.8, 3.63)))
        _cap_mobs.append(_cap_0)
        _ptr_0 = VGroup().set_z_index(19)
        _ptr_0.add_updater(lambda m: _cap_point_update(m, _cap_0, lambda: bob, 1.8, 3.63))
        _cap_mobs.append(_ptr_0)
        _cap_1 = Text('The graph traces its angle θ(t) in step', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_1.width > 13.4:
            _cap_1.scale_to_fit_width(13.4)
        if _cap_1.height > 0.9:
            _cap_1.scale_to_fit_height(0.9)
        _cap_1.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 3.83, 5.67)))
        _cap_mobs.append(_cap_1)
        _ptr_1 = VGroup().set_z_index(19)
        _ptr_1.add_updater(lambda m: _cap_point_update(m, _cap_1, lambda: readout, 3.83, 5.67))
        _cap_mobs.append(_ptr_1)
        _cap_2 = Text('Friction shrinks every swing a little', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_2.width > 13.4:
            _cap_2.scale_to_fit_width(13.4)
        if _cap_2.height > 0.9:
            _cap_2.scale_to_fit_height(0.9)
        _cap_2.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 5.87, 7.7)))
        _cap_mobs.append(_cap_2)
        _ptr_2 = VGroup().set_z_index(19)
        _ptr_2.add_updater(lambda m: _cap_point_update(m, _cap_2, lambda: readout, 5.87, 7.7))
        _cap_mobs.append(_ptr_2)
        self.add(*_cap_mobs)

        ts = [0.0, 0.07547, 0.15094, 0.22642, 0.30189, 0.37736, 0.45283, 0.5283, 0.60377, 0.67925, 0.75472, 0.83019, 0.90566, 0.98113, 1.0566, 1.13208, 1.20755, 1.28302, 1.35849, 1.43396, 1.50943, 1.58491, 1.66038, 1.73585, 1.81132, 1.88679, 1.96226, 2.03774, 2.11321, 2.18868, 2.26415, 2.33962, 2.41509, 2.49057, 2.56604, 2.64151, 2.71698, 2.79245, 2.86792, 2.9434, 3.01887, 3.09434, 3.16981, 3.24528, 3.32075, 3.39623, 3.4717, 3.54717, 3.62264, 3.69811, 3.77358, 3.84906, 3.92453, 4.0, 4.07547, 4.15094, 4.22642, 4.30189, 4.37736, 4.45283, 4.5283, 4.60377, 4.67925, 4.75472, 4.83019, 4.90566, 4.98113, 5.0566, 5.13208, 5.20755, 5.28302, 5.35849, 5.43396, 5.50943, 5.58491, 5.66038, 5.73585, 5.81132, 5.88679, 5.96226, 6.03774, 6.11321, 6.18868, 6.26415, 6.33962, 6.41509, 6.49057, 6.56604, 6.64151, 6.71698, 6.79245, 6.86792, 6.9434, 7.01887, 7.09434, 7.16981, 7.24528, 7.32075, 7.39623, 7.4717, 7.54717, 7.62264, 7.69811, 7.77358, 7.84906, 7.92453, 8.0, 8.07547, 8.15094, 8.22642, 8.30189, 8.37736, 8.45283, 8.5283, 8.60377, 8.67925, 8.75472, 8.83019, 8.90566, 8.98113, 9.0566, 9.13208, 9.20755, 9.28302, 9.35849, 9.43396, 9.50943, 9.58491, 9.66038, 9.73585, 9.81132, 9.88679, 9.96226, 10.03774, 10.11321, 10.18868, 10.26415, 10.33962, 10.41509, 10.49057, 10.56604, 10.64151, 10.71698, 10.79245, 10.86792, 10.9434, 11.01887, 11.09434, 11.16981, 11.24528, 11.32075, 11.39623, 11.4717, 11.54717, 11.62264, 11.69811, 11.77358, 11.84906, 11.92453, 12.0]
        ths = [1.0, 0.97669, 0.90804, 0.79713, 0.64878, 0.46983, 0.26921, 0.05757, -0.15342, -0.35223, -0.52851, -0.67388, -0.78225, -0.8498, -0.87468, -0.85675, -0.79742, -0.69969, -0.56822, -0.40947, -0.23168, -0.04446, 0.14185, 0.31704, 0.47193, 0.59902, 0.69276, 0.74959, 0.76781, 0.74737, 0.68979, 0.59814, 0.47711, 0.33297, 0.17343, 0.00726, -0.15632, -0.30841, -0.44106, -0.54781, -0.62395, -0.6665, -0.67417, -0.64727, -0.58759, -0.49841, -0.3845, -0.25197, -0.10811, 0.03911, 0.18154, 0.31147, 0.4222, 0.50836, 0.56615, 0.59331, 0.58915, 0.55441, 0.49127, 0.40326, 0.29521, 0.17307, 0.04365, -0.08585, -0.20831, -0.31718, -0.40691, -0.47323, -0.51322, -0.52543, -0.50975, -0.46744, -0.40105, -0.31434, -0.21215, -0.1002, 0.01525, 0.12778, 0.23128, 0.3203, 0.39036, 0.4382, 0.46178, 0.46038, 0.43449, 0.38587, 0.31737, 0.2329, 0.13724, 0.03576, -0.06587, -0.16205, -0.24761, -0.31814, -0.37016, -0.4013, -0.41035, -0.39724, -0.36303, -0.30987, -0.24085, -0.15993, -0.07168, 0.01892, 0.10685, 0.18733, 0.25611, 0.30969, 0.34551, 0.36202, 0.3587, 0.33609, 0.2957, 0.23998, 0.17216, 0.09612, 0.01615, -0.06326, -0.13777, -0.20338, -0.25668, -0.29503, -0.31666, -0.32074, -0.30736, -0.27754, -0.23316, -0.17684, -0.11184, -0.04185, 0.02918, 0.09733, 0.15891, 0.21065, 0.24995, 0.27491, 0.28445, 0.27835, 0.25722, 0.22244, 0.17613, 0.12099, 0.06019, -0.00283, -0.06457, -0.12164, -0.171, -0.21009, -0.23699, -0.25047, -0.25004, -0.23598, -0.20928, -0.17161, -0.1252, -0.07275, -0.01723, 0.03824, 0.0906, 0.13705]
        rod_len = 2.0
        pivot = np.array([-3.3, 1.4, 0.0])

        title = Text('Explain the small-angle pendulum and its period dependence.').scale(0.5).to_edge(UP)

        t_tracker = ValueTracker(float(ts[0]))

        def theta_now():
            return float(np.interp(t_tracker.get_value(), ts, ths))

        def bob_point():
            th = theta_now()
            return pivot + rod_len * np.array([np.sin(th), -np.cos(th), 0.0])

        anchor = Dot(pivot, color=GREY_B, radius=0.05)
        rod = always_redraw(lambda: Line(pivot, bob_point(), color=GREY_A, stroke_width=3))
        bob = always_redraw(lambda: Dot(bob_point(), color=YELLOW, radius=0.16))
        trail = TracedPath(bob_point, stroke_color=TEAL, stroke_width=2.5, dissipating_time=1.6)

        # theta(t) read-out on the right, drawn in sync with the swing.
        axes = Axes(
            x_range=[float(ts[0]), float(ts[-1]), (float(ts[-1]) - float(ts[0])) / 4.0],
            y_range=[-max(abs(min(ths)), abs(max(ths))) * 1.2 - 1e-6,
                     max(abs(min(ths)), abs(max(ths))) * 1.2 + 1e-6,
                     max(abs(min(ths)), abs(max(ths))) / 2.0 + 1e-6],
            x_length=5.0, y_length=3.0,
            axis_config={"include_tip": False, "stroke_opacity": 0.5},
        ).to_corner(DR, buff=0.6)
        y_label = axes.get_y_axis_label(Text("theta").scale(0.35))
        trace_pts = [axes.coords_to_point(t, th) for t, th in zip(ts, ths)]
        trace = VMobject(color=TEAL, stroke_width=3)
        trace.set_points_smoothly(trace_pts)
        readout = always_redraw(lambda: Dot(
            axes.coords_to_point(t_tracker.get_value(), theta_now()),
            color=YELLOW, radius=0.06))

        self.play(FadeIn(title), Create(axes), FadeIn(y_label), run_time=1.0)
        self.add(anchor, rod, bob, trail)
        self.play(GrowFromCenter(bob), run_time=0.5)
        self.add(readout)
        self.play(
            t_tracker.animate.set_value(float(ts[-1])),
            Create(trace),
            run_time=6.0, rate_func=linear,
        )
        self.wait(0.5)

        # AetherLab explanation layer: keep the animation as a thumbnail and explain beside it.
        self.remove(_clock, _cap_band, *_cap_mobs)
        for _m in self.mobjects:
            _m.clear_updaters()
        _stage = Group(*self.mobjects)
        if len(_stage) and _stage.width > 0.1:
            _s = min(4.8 / _stage.width, 3.3 / max(_stage.height, 0.1), 1.0)
            self.play(_stage.animate.scale(_s).to_corner(UL, buff=0.45), run_time=1.0)
        _thumb_box = SurroundingRectangle(_stage, color=GREY_B, buff=0.12, stroke_width=1.5, corner_radius=0.08)
        _eq = Text("θ'' = -(g/L)·sin θ - 2γ·θ'", font_size=24, color=WHITE)
        _eq.next_to(_thumb_box, DOWN, buff=0.35).align_to(_thumb_box, LEFT)
        if _eq.width > 4.9:
            _eq.scale_to_fit_width(4.9)
        if _eq.height > 2.0:
            _eq.scale_to_fit_height(2.0)
        self.play(Create(_thumb_box), FadeIn(_eq), run_time=0.6)
        _side_w = max(4.0, 6.9 - _thumb_box.get_right()[0])

        # Beat A: the prediction's answer, then the misconception confronted.
        _pa_head = Text('The answer', font_size=30, weight=BOLD, color=YELLOW)
        _pa_text = Text("It stays the same. Mass cancels out of θ'' =\n-(g/L)·sin θ, so only L, g and the swing\nsize matter.", font_size=24, color=WHITE)
        _mis_head = Text('Common idea', font_size=24, weight=BOLD, color=RED_B)
        _mis_wrong = Text('A heavier bob swings faster.', font_size=24, color=RED_A)
        _mis_fix_head = Text('What actually happens', font_size=24, weight=BOLD, color=GREEN_B)
        _mis_fix = Text('Gravity pulls harder on a heavier bob, but\nit is also harder to accelerate. The two\ncancel.', font_size=24, color=GREEN_A)
        _beat_a = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong, _mis_fix_head, _mis_fix).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        if _beat_a.width > _side_w:
            _beat_a.scale_to_fit_width(_side_w)
        if _beat_a.height > 6.6:
            _beat_a.scale_to_fit_height(6.6)
        _beat_a.next_to(_thumb_box, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        _first = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong)
        self.play(FadeIn(_first, shift=0.2 * LEFT), run_time=0.8)
        self.wait(1.2)
        _cross = Cross(_mis_wrong, stroke_color=RED, stroke_width=4)
        self.play(Create(_cross), FadeIn(_mis_fix_head), FadeIn(_mis_fix), run_time=0.8)
        self.wait(1.8)
        self.play(FadeOut(_beat_a), FadeOut(_cross), run_time=0.5)

        # Beat B: the key numbers and the takeaway, beside the thumbnail.
        _head = Text('What the animation shows', font_size=30, weight=BOLD, color=YELLOW)
        _facts = VGroup(Text('Released from 57 degrees, with L = 1.00 m\nand g = 9.81 m/s²', font_size=23, color=GREY_A), Text('Small-angle formula: T = 2π·√(L/g) = 2.01 s', font_size=23, color=GREY_A), Text('First swing measured from this simulation:\n2.10 s', font_size=23, color=GREY_A), Text('Friction shrinks the swing to about 16\ndegrees by t = 12 s', font_size=23, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.26)
        _key = Text('The period depends on L and g, not on the\nmass. Wide swings take longer than the\nsmall-angle formula predicts.', font_size=24, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.2, corner_radius=0.12)
        _beat_b = VGroup(_head, _facts, VGroup(_key, _key_box)).arrange(DOWN, aligned_edge=LEFT, buff=0.34)
        if _beat_b.width > _side_w:
            _beat_b.scale_to_fit_width(_side_w)
        if _beat_b.height > 6.6:
            _beat_b.scale_to_fit_height(6.6)
        _beat_b.next_to(_thumb_box, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        self.play(FadeIn(_head, shift=0.2 * DOWN), run_time=0.8)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=4.4)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.0)
        self.wait(2.0)
