"""Generated by AetherLab - double-slit interference (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Double-slit interference', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('I(θ) ∝ cos²(π·d·sin θ / λ)', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: waves spread from both slits and build the\nbright and dark bands on the screen.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.2)
        self.wait(4.3)
        self.play(FadeOut(_intro), run_time=0.6)

        title = Text('Show double-slit interference and the resulting fringe patt…').scale(0.46).to_edge(UP)

        slit_x = -4.6
        gap = 1.1
        top = np.array([slit_x, gap, 0.0])
        bot = np.array([slit_x, -gap, 0.0])

        # Barrier with two slits.
        barrier = VGroup(
            Line([slit_x, 3.2, 0.0], [slit_x, gap + 0.28, 0.0], color=GREY_B, stroke_width=6),
            Line([slit_x, gap - 0.28, 0.0], [slit_x, -gap + 0.28, 0.0], color=GREY_B, stroke_width=6),
            Line([slit_x, -gap - 0.28, 0.0], [slit_x, -3.2, 0.0], color=GREY_B, stroke_width=6),
        )
        s_top = Dot(top, color=YELLOW, radius=0.08)
        s_bot = Dot(bot, color=YELLOW, radius=0.08)

        # Expanding circular wavefronts from each slit.
        r = ValueTracker(0.0)

        def rings(center):
            def make():
                grp = VGroup()
                for i in range(5):
                    rad = r.get_value() - i * 1.15
                    if 0.05 < rad < 9.0:
                        grp.add(Arc(radius=rad, start_angle=-PI / 2.2, angle=PI / 1.1,
                                    arc_center=center, color=TEAL,
                                    stroke_width=2, stroke_opacity=0.6))
                return grp
            return make

        waves_top = always_redraw(rings(top))
        waves_bot = always_redraw(rings(bot))

        # Screen on the right and the interference intensity pattern.
        screen_x = 5.0
        screen = Line([screen_x, 3.2, 0.0], [screen_x, -3.2, 0.0], color=GREY_A, stroke_width=4)
        ys = np.linspace(-3.0, 3.0, 240)
        inten = np.cos(1.9 * ys) ** 2
        pattern = VMobject(color=BLUE_C, stroke_width=3)
        pattern.set_points_smoothly(
            [np.array([screen_x - 1.4 * v, y, 0.0]) for y, v in zip(ys, inten)]
        )
        # Bright-fringe markers at the intensity maxima.
        fringes = VGroup(*[
            Dot([screen_x, y, 0.0], color=YELLOW, radius=0.06)
            for y in ys[1:-1][(inten[1:-1] > inten[:-2]) & (inten[1:-1] > inten[2:])]
        ])
        caption = Text("bright where path difference = n*lambda", color=GREY_A).scale(0.28)
        caption.to_edge(DOWN)

        self.play(FadeIn(title), Create(barrier), FadeIn(s_top), FadeIn(s_bot),
                  Create(screen), run_time=1.2)
        self.add(waves_top, waves_bot)
        self.play(r.animate.set_value(11.0), run_time=4.0, rate_func=linear)
        self.play(Create(pattern), run_time=1.4)
        self.play(LaggedStart(*[GrowFromCenter(f) for f in fringes], lag_ratio=0.06),
                  FadeIn(caption), run_time=1.4)
        self.wait(0.5)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in self.mobjects:
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(*self.mobjects), run_time=0.8)
        _head = Text('What the animation shows', font_size=34, weight=BOLD, color=YELLOW)
        _eq = Text('I(θ) ∝ cos²(π·d·sin θ / λ)', font_size=28, color=WHITE)
        _facts = VGroup(Text('Bright bands where the path difference d·sin θ = m·λ', font_size=25, color=GREY_A), Text('Dark bands where it is (m + ½)·λ: crest meets trough', font_size=25, color=GREY_A), Text('Band spacing Δy = λL/d: closer slits or longer λ spread the bands', font_size=25, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _key = Text('Waves from the two slits add where crests meet and cancel where crest\nmeets trough. The band pattern is the signature of wave behaviour.', font_size=27, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.42)
        if _card.width > 12.4:
            _card.scale_to_fit_width(12.4)
        if _card.height > 7.0:
            _card.scale_to_fit_height(7.0)
        self.play(FadeIn(_head, shift=0.2 * DOWN), FadeIn(_eq), run_time=1.2)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=4.2)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.2)
        self.wait(8.0)
