"""Generated by AetherLab - double-slit interference (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Double-slit interference', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('I(θ) ∝ cos²(π·d·sin θ / λ)', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: waves spread from both slits and build the\nbright and dark bands on the screen.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.0)
        self.wait(1.8)
        self.play(FadeOut(_intro), run_time=0.5)

        # AetherLab explanation layer: predict before the reveal.
        _pq_head = Text('Predict first', font_size=34, weight=BOLD, color=YELLOW)
        _pq_text = Text('Light passes through two narrow slits. How many\nbright bands appear on the screen?', font_size=30, color=WHITE)
        _pq_hint = Text('Decide before you watch.', font_size=24, color=GREY_B)
        _pq_bar = Line(3 * LEFT, 3 * RIGHT, color=YELLOW, stroke_width=6)
        _pq_card = VGroup(_pq_head, _pq_text, _pq_hint, _pq_bar).arrange(DOWN, buff=0.45)
        if _pq_card.width > 12.4:
            _pq_card.scale_to_fit_width(12.4)
        if _pq_card.height > 7.0:
            _pq_card.scale_to_fit_height(7.0)
        self.play(FadeIn(_pq_card, shift=0.2 * UP), run_time=0.8)
        self.play(_pq_bar.animate.scale(0.01, about_edge=LEFT), run_time=2.5, rate_func=linear)
        self.play(FadeOut(_pq_card), run_time=0.5)

        # AetherLab explanation layer: timed captions during the animation, with a
        # highlight ring and pointer on the object each caption describes.
        _clock = ValueTracker(0.0)
        _clock.add_updater(lambda m, dt: m.increment_value(dt))
        self.add(_clock)

        def _cap_alpha(t, a, b):
            return max(0.0, min(1.0, (t - a) / 0.35, (b - t) / 0.35))

        def _cap_pointer(cap, target, alpha):
            end = target.get_center()
            ring = Circle(radius=0.32, color=YELLOW_A, stroke_width=3).move_to(end)
            ring.set_stroke(opacity=alpha)
            start = cap.get_bottom() + 0.12 * DOWN
            if np.linalg.norm(end - start) < 0.9:
                return VGroup(ring).set_z_index(19)
            line = DashedLine(start, end, buff=0.36, color=YELLOW_A, stroke_width=2)
            line.set_stroke(opacity=0.8 * alpha)
            return VGroup(line, ring).set_z_index(19)

        def _cap_point_update(m, cap, target_fn, a, b):
            # The target is looked up lazily: it is only created by the
            # animation below, after this setup code has run.
            alpha = _cap_alpha(_clock.get_value(), a, b)
            if alpha <= 0:
                m.set_stroke(opacity=0)
                return
            try:
                target = target_fn()
            except NameError:
                return
            # Refresh the target first; otherwise the ring trails a moving
            # object by one frame (this updater can run before the target's).
            target.update(0)
            m.become(_cap_pointer(cap, target, alpha))

        _cap_band = Rectangle(width=14.6, height=1.0, stroke_width=0, fill_color=BLACK, fill_opacity=0.0).to_edge(UP, buff=0).set_z_index(20)
        _cap_band.add_updater(lambda m: m.set_fill(BLACK, opacity=_cap_alpha(_clock.get_value(), 0.95, 8.2)))
        self.add(_cap_band)
        _cap_mobs = []
        _cap_0 = Text('Each slit acts as a new source of waves', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_0.width > 13.4:
            _cap_0.scale_to_fit_width(13.4)
        if _cap_0.height > 0.9:
            _cap_0.scale_to_fit_height(0.9)
        _cap_0.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 0.95, 3.23)))
        _cap_mobs.append(_cap_0)
        _ptr_0 = VGroup().set_z_index(19)
        _ptr_0.add_updater(lambda m: _cap_point_update(m, _cap_0, lambda: s_top, 0.95, 3.23))
        _cap_mobs.append(_ptr_0)
        _cap_1 = Text('Crest meets crest: bright. Crest meets trough: dark', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_1.width > 13.4:
            _cap_1.scale_to_fit_width(13.4)
        if _cap_1.height > 0.9:
            _cap_1.scale_to_fit_height(0.9)
        _cap_1.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 3.43, 5.72)))
        _cap_mobs.append(_cap_1)
        _cap_2 = Text('The screen records the band pattern', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_2.width > 13.4:
            _cap_2.scale_to_fit_width(13.4)
        if _cap_2.height > 0.9:
            _cap_2.scale_to_fit_height(0.9)
        _cap_2.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 5.92, 8.2)))
        _cap_mobs.append(_cap_2)
        _ptr_2 = VGroup().set_z_index(19)
        _ptr_2.add_updater(lambda m: _cap_point_update(m, _cap_2, lambda: screen, 5.92, 8.2))
        _cap_mobs.append(_ptr_2)
        self.add(*_cap_mobs)

        title = Text('Show double-slit interference and the resulting fringe patt…').scale(0.46).to_edge(UP)

        slit_x = -4.6
        gap = 1.1
        top = np.array([slit_x, gap, 0.0])
        bot = np.array([slit_x, -gap, 0.0])

        # Barrier with two slits.
        barrier = VGroup(
            Line([slit_x, 3.2, 0.0], [slit_x, gap + 0.28, 0.0], color=GREY_B, stroke_width=6),
            Line([slit_x, gap - 0.28, 0.0], [slit_x, -gap + 0.28, 0.0], color=GREY_B, stroke_width=6),
            Line([slit_x, -gap - 0.28, 0.0], [slit_x, -3.2, 0.0], color=GREY_B, stroke_width=6),
        )
        s_top = Dot(top, color=YELLOW, radius=0.08)
        s_bot = Dot(bot, color=YELLOW, radius=0.08)

        # Expanding circular wavefronts from each slit.
        r = ValueTracker(0.0)

        def rings(center):
            def make():
                grp = VGroup()
                for i in range(5):
                    rad = r.get_value() - i * 1.15
                    if 0.05 < rad < 9.0:
                        grp.add(Arc(radius=rad, start_angle=-PI / 2.2, angle=PI / 1.1,
                                    arc_center=center, color=TEAL,
                                    stroke_width=2, stroke_opacity=0.6))
                return grp
            return make

        waves_top = always_redraw(rings(top))
        waves_bot = always_redraw(rings(bot))

        # Screen on the right and the interference intensity pattern.
        screen_x = 5.0
        screen = Line([screen_x, 3.2, 0.0], [screen_x, -3.2, 0.0], color=GREY_A, stroke_width=4)
        ys = np.linspace(-3.0, 3.0, 240)
        inten = np.cos(1.9 * ys) ** 2
        pattern = VMobject(color=BLUE_C, stroke_width=3)
        pattern.set_points_smoothly(
            [np.array([screen_x - 1.4 * v, y, 0.0]) for y, v in zip(ys, inten)]
        )
        # Bright-fringe markers at the intensity maxima.
        fringes = VGroup(*[
            Dot([screen_x, y, 0.0], color=YELLOW, radius=0.06)
            for y in ys[1:-1][(inten[1:-1] > inten[:-2]) & (inten[1:-1] > inten[2:])]
        ])
        caption = Text("bright where path difference = n*lambda", color=GREY_A).scale(0.28)
        caption.to_edge(DOWN)

        self.play(FadeIn(title), Create(barrier), FadeIn(s_top), FadeIn(s_bot),
                  Create(screen), run_time=1.2)
        self.add(waves_top, waves_bot)
        self.play(r.animate.set_value(11.0), run_time=4.0, rate_func=linear)
        self.play(Create(pattern), run_time=1.4)
        self.play(LaggedStart(*[GrowFromCenter(f) for f in fringes], lag_ratio=0.06),
                  FadeIn(caption), run_time=1.4)
        self.wait(0.5)

        # AetherLab explanation layer: keep the animation as a thumbnail and explain beside it.
        self.remove(_clock, _cap_band, *_cap_mobs)
        for _m in self.mobjects:
            _m.clear_updaters()
        _stage = Group(*self.mobjects)
        if len(_stage) and _stage.width > 0.1:
            _s = min(4.8 / _stage.width, 3.3 / max(_stage.height, 0.1), 1.0)
            self.play(_stage.animate.scale(_s).to_corner(UL, buff=0.45), run_time=1.0)
        _thumb_box = SurroundingRectangle(_stage, color=GREY_B, buff=0.12, stroke_width=1.5, corner_radius=0.08)
        _eq = Text('I(θ) ∝ cos²(π·d·sin θ / λ)', font_size=24, color=WHITE)
        _eq.next_to(_thumb_box, DOWN, buff=0.35).align_to(_thumb_box, LEFT)
        if _eq.width > 4.9:
            _eq.scale_to_fit_width(4.9)
        if _eq.height > 2.0:
            _eq.scale_to_fit_height(2.0)
        self.play(Create(_thumb_box), FadeIn(_eq), run_time=0.6)
        _side_w = max(4.0, 6.9 - _thumb_box.get_right()[0])

        # Beat A: the prediction's answer, then the misconception confronted.
        _pa_head = Text('The answer', font_size=30, weight=BOLD, color=YELLOW)
        _pa_text = Text('Many, not two. Bright bands appear wherever\nthe two paths differ by a whole number of\nwavelengths.', font_size=24, color=WHITE)
        _mis_head = Text('Common idea', font_size=24, weight=BOLD, color=RED_B)
        _mis_wrong = Text('Two slits give two bright stripes.', font_size=24, color=RED_A)
        _mis_fix_head = Text('What actually happens', font_size=24, weight=BOLD, color=GREEN_B)
        _mis_fix = Text('Waves from both slits overlap everywhere, so\na whole row of bright and dark bands forms.', font_size=24, color=GREEN_A)
        _beat_a = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong, _mis_fix_head, _mis_fix).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        if _beat_a.width > _side_w:
            _beat_a.scale_to_fit_width(_side_w)
        if _beat_a.height > 6.6:
            _beat_a.scale_to_fit_height(6.6)
        _beat_a.next_to(_thumb_box, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        _first = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong)
        self.play(FadeIn(_first, shift=0.2 * LEFT), run_time=0.8)
        self.wait(1.2)
        _cross = Cross(_mis_wrong, stroke_color=RED, stroke_width=4)
        self.play(Create(_cross), FadeIn(_mis_fix_head), FadeIn(_mis_fix), run_time=0.8)
        self.wait(1.8)
        self.play(FadeOut(_beat_a), FadeOut(_cross), run_time=0.5)

        # Beat B: the key numbers and the takeaway, beside the thumbnail.
        _head = Text('What the animation shows', font_size=30, weight=BOLD, color=YELLOW)
        _facts = VGroup(Text('Bright bands where the path difference d·sin\nθ = m·λ', font_size=23, color=GREY_A), Text('Dark bands where it is (m + ½)·λ: crest\nmeets trough', font_size=23, color=GREY_A), Text('Band spacing Δy = λL/d: closer slits or\nlonger λ spread the bands', font_size=23, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.26)
        _key = Text('Waves from the two slits add where crests\nmeet and cancel where crest meets trough.\nThe band pattern is the signature of wave\nbehaviour.', font_size=24, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.2, corner_radius=0.12)
        _beat_b = VGroup(_head, _facts, VGroup(_key, _key_box)).arrange(DOWN, aligned_edge=LEFT, buff=0.34)
        if _beat_b.width > _side_w:
            _beat_b.scale_to_fit_width(_side_w)
        if _beat_b.height > 6.6:
            _beat_b.scale_to_fit_height(6.6)
        _beat_b.next_to(_thumb_box, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        self.play(FadeIn(_head, shift=0.2 * DOWN), run_time=0.8)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=3.3)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.0)
        self.wait(2.6)
