"""Generated by AetherLab - standing wave (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Standing wave: normal mode n = 3', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('y(x,t) = 2A·sin(nπx/L)·cos(ωt)', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: the nodes stay still while the string breathes\nbetween the dashed envelopes.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.0)
        self.wait(1.8)
        self.play(FadeOut(_intro), run_time=0.5)

        # AetherLab explanation layer: predict before the reveal.
        _pq_head = Text('Predict first', font_size=34, weight=BOLD, color=YELLOW)
        _pq_text = Text('The string is vibrating. Do the red points ever\nmove?', font_size=30, color=WHITE)
        _pq_hint = Text('Decide before you watch.', font_size=24, color=GREY_B)
        _pq_bar = Line(3 * LEFT, 3 * RIGHT, color=YELLOW, stroke_width=6)
        _pq_card = VGroup(_pq_head, _pq_text, _pq_hint, _pq_bar).arrange(DOWN, buff=0.45)
        if _pq_card.width > 12.4:
            _pq_card.scale_to_fit_width(12.4)
        if _pq_card.height > 7.0:
            _pq_card.scale_to_fit_height(7.0)
        self.play(FadeIn(_pq_card, shift=0.2 * UP), run_time=0.8)
        self.play(_pq_bar.animate.scale(0.01, about_edge=LEFT), run_time=2.5, rate_func=linear)
        self.play(FadeOut(_pq_card), run_time=0.5)

        # AetherLab explanation layer: timed captions during the animation, with a
        # highlight ring and pointer on the object each caption describes.
        _clock = ValueTracker(0.0)
        _clock.add_updater(lambda m, dt: m.increment_value(dt))
        self.add(_clock)

        def _cap_alpha(t, a, b):
            return max(0.0, min(1.0, (t - a) / 0.35, (b - t) / 0.35))

        def _cap_pointer(cap, target, alpha):
            end = target.get_center()
            ring = Circle(radius=0.32, color=YELLOW_A, stroke_width=3).move_to(end)
            ring.set_stroke(opacity=alpha)
            start = cap.get_bottom() + 0.12 * DOWN
            if np.linalg.norm(end - start) < 0.9:
                return VGroup(ring).set_z_index(19)
            line = DashedLine(start, end, buff=0.36, color=YELLOW_A, stroke_width=2)
            line.set_stroke(opacity=0.8 * alpha)
            return VGroup(line, ring).set_z_index(19)

        def _cap_point_update(m, cap, target_fn, a, b):
            # The target is looked up lazily: it is only created by the
            # animation below, after this setup code has run.
            alpha = _cap_alpha(_clock.get_value(), a, b)
            if alpha <= 0:
                m.set_stroke(opacity=0)
                return
            try:
                target = target_fn()
            except NameError:
                return
            # Refresh the target first; otherwise the ring trails a moving
            # object by one frame (this updater can run before the target's).
            target.update(0)
            m.become(_cap_pointer(cap, target, alpha))

        _cap_band = Rectangle(width=14.6, height=1.0, stroke_width=0, fill_color=BLACK, fill_opacity=0.0).to_edge(UP, buff=0).set_z_index(20)
        _cap_band.add_updater(lambda m: m.set_fill(BLACK, opacity=_cap_alpha(_clock.get_value(), 3.2, 9.0)))
        self.add(_cap_band)
        _cap_mobs = []
        _cap_0 = Text('Red nodes never move', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_0.width > 13.4:
            _cap_0.scale_to_fit_width(13.4)
        if _cap_0.height > 0.9:
            _cap_0.scale_to_fit_height(0.9)
        _cap_0.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 3.2, 5.0)))
        _cap_mobs.append(_cap_0)
        _ptr_0 = VGroup().set_z_index(19)
        _ptr_0.add_updater(lambda m: _cap_point_update(m, _cap_0, lambda: nodes, 3.2, 5.0))
        _cap_mobs.append(_ptr_0)
        _cap_1 = Text('Yellow antinodes swing the most', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_1.width > 13.4:
            _cap_1.scale_to_fit_width(13.4)
        if _cap_1.height > 0.9:
            _cap_1.scale_to_fit_height(0.9)
        _cap_1.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 5.2, 7.0)))
        _cap_mobs.append(_cap_1)
        _ptr_1 = VGroup().set_z_index(19)
        _ptr_1.add_updater(lambda m: _cap_point_update(m, _cap_1, lambda: antinodes, 5.2, 7.0))
        _cap_mobs.append(_ptr_1)
        _cap_2 = Text('Every point moves in place; nothing travels', font_size=28, color=YELLOW_A).move_to(_cap_band).set_z_index(21).set_opacity(0.0)
        if _cap_2.width > 13.4:
            _cap_2.scale_to_fit_width(13.4)
        if _cap_2.height > 0.9:
            _cap_2.scale_to_fit_height(0.9)
        _cap_2.add_updater(lambda m: m.set_opacity(_cap_alpha(_clock.get_value(), 7.2, 9.0)))
        _cap_mobs.append(_cap_2)
        self.add(*_cap_mobs)

        n = 3
        title = Text('Show a standing wave forming from two travelling waves on a…').scale(0.46).to_edge(UP)

        length = 10.0
        amp = 1.4
        x0 = -length / 2.0

        def y_of(x, phase):
            xi = x - x0
            return amp * np.sin(n * PI * xi / length) * np.cos(phase)

        axis = Line([x0, 0, 0], [x0 + length, 0, 0], color=GREY_B,
                    stroke_width=2, stroke_opacity=0.5)
        wall_l = Line([x0, -1.8, 0], [x0, 1.8, 0], color=GREY_A, stroke_width=5)
        wall_r = Line([x0 + length, -1.8, 0], [x0 + length, 1.8, 0], color=GREY_A, stroke_width=5)

        grid = np.linspace(x0, x0 + length, 160)
        phase = ValueTracker(0.0)

        def string():
            pts = [np.array([x, y_of(x, phase.get_value()), 0.0]) for x in grid]
            m = VMobject(color=TEAL, stroke_width=4)
            m.set_points_smoothly(pts)
            return m

        wave = always_redraw(string)
        # Envelope (the standing-wave amplitude profile) as a dashed ghost.
        env_hi = DashedVMobject(VMobject(color=BLUE_C, stroke_width=2).set_points_smoothly(
            [np.array([x, abs(amp * np.sin(n * PI * (x - x0) / length)), 0.0]) for x in grid]))
        env_lo = DashedVMobject(VMobject(color=BLUE_C, stroke_width=2).set_points_smoothly(
            [np.array([x, -abs(amp * np.sin(n * PI * (x - x0) / length)), 0.0]) for x in grid]))

        # Nodes (fixed) and antinodes (max swing).
        nodes = VGroup(*[Dot([x0 + length * k / n, 0, 0], color=RED, radius=0.07)
                         for k in range(n + 1)])
        antinodes = VGroup(*[Dot([x0 + length * (k + 0.5) / n, 0, 0], color=YELLOW, radius=0.06)
                             for k in range(n)])
        node_lbl = Text("nodes (fixed)", color=RED).scale(0.3).to_corner(DL, buff=0.6)

        self.play(FadeIn(title), Create(axis), Create(wall_l), Create(wall_r), run_time=1.0)
        self.play(Create(env_hi), Create(env_lo), run_time=0.9)
        self.add(wave)
        self.play(LaggedStart(*[GrowFromCenter(d) for d in nodes], lag_ratio=0.1),
                  FadeIn(node_lbl), run_time=1.0)
        self.add(antinodes)
        self.play(phase.animate.set_value(3.0 * TAU), run_time=6.0, rate_func=linear)
        self.wait(0.4)

        # AetherLab explanation layer: keep the animation as a thumbnail and explain beside it.
        self.remove(_clock, _cap_band, *_cap_mobs)
        for _m in self.mobjects:
            _m.clear_updaters()
        _stage = Group(*self.mobjects)
        if len(_stage) and _stage.width > 0.1:
            _s = min(4.8 / _stage.width, 3.3 / max(_stage.height, 0.1), 1.0)
            self.play(_stage.animate.scale(_s).to_corner(UL, buff=0.45), run_time=1.0)
        _thumb_box = SurroundingRectangle(_stage, color=GREY_B, buff=0.12, stroke_width=1.5, corner_radius=0.08)
        _eq = Text('y(x,t) = 2A·sin(nπx/L)·cos(ωt)', font_size=24, color=WHITE)
        _eq.next_to(_thumb_box, DOWN, buff=0.35).align_to(_thumb_box, LEFT)
        if _eq.width > 4.9:
            _eq.scale_to_fit_width(4.9)
        if _eq.height > 2.0:
            _eq.scale_to_fit_height(2.0)
        self.play(Create(_thumb_box), FadeIn(_eq), run_time=0.6)
        _side_w = max(4.0, 6.9 - _thumb_box.get_right()[0])

        # Beat A: the prediction's answer, then the misconception confronted.
        _pa_head = Text('The answer', font_size=30, weight=BOLD, color=YELLOW)
        _pa_text = Text('Never. Nodes stay still; every other point\nmoves up and down in place, and nothing\ntravels along the string.', font_size=24, color=WHITE)
        _mis_head = Text('Common idea', font_size=24, weight=BOLD, color=RED_B)
        _mis_wrong = Text('A standing wave carries energy along the\nstring.', font_size=24, color=RED_A)
        _mis_fix_head = Text('What actually happens', font_size=24, weight=BOLD, color=GREEN_B)
        _mis_fix = Text('Its two travelling halves carry equal energy\nin opposite directions, so the net flow is\nzero.', font_size=24, color=GREEN_A)
        _beat_a = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong, _mis_fix_head, _mis_fix).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        if _beat_a.width > _side_w:
            _beat_a.scale_to_fit_width(_side_w)
        if _beat_a.height > 6.6:
            _beat_a.scale_to_fit_height(6.6)
        _beat_a.next_to(_thumb_box, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        _first = VGroup(_pa_head, _pa_text, _mis_head, _mis_wrong)
        self.play(FadeIn(_first, shift=0.2 * LEFT), run_time=0.8)
        self.wait(1.2)
        _cross = Cross(_mis_wrong, stroke_color=RED, stroke_width=4)
        self.play(Create(_cross), FadeIn(_mis_fix_head), FadeIn(_mis_fix), run_time=0.8)
        self.wait(1.8)
        self.play(FadeOut(_beat_a), FadeOut(_cross), run_time=0.5)

        # Beat B: the key numbers and the takeaway, beside the thumbnail.
        _head = Text('What the animation shows', font_size=30, weight=BOLD, color=YELLOW)
        _facts = VGroup(Text('Mode n = 3: 4 nodes (including the fixed\nends) and 3 antinodes', font_size=23, color=GREY_A), Text('Wavelength λ = 2L/n = 0.67·L', font_size=23, color=GREY_A), Text('Frequency f = n·f₁ = 3·f₁', font_size=23, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.26)
        _key = Text('Two equal waves travelling in opposite\ndirections add up to a standing wave. Only\nwhole numbers of half-wavelengths fit: L =\nn·λ/2.', font_size=24, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.2, corner_radius=0.12)
        _beat_b = VGroup(_head, _facts, VGroup(_key, _key_box)).arrange(DOWN, aligned_edge=LEFT, buff=0.34)
        if _beat_b.width > _side_w:
            _beat_b.scale_to_fit_width(_side_w)
        if _beat_b.height > 6.6:
            _beat_b.scale_to_fit_height(6.6)
        _beat_b.next_to(_thumb_box, RIGHT, buff=0.55).align_to(_thumb_box, UP)
        self.play(FadeIn(_head, shift=0.2 * DOWN), run_time=0.8)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=3.3)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.0)
        self.wait(1.8)
