"""Generated by AetherLab - scenario: a square wave, one circle at a time."""

import math

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('A square wave, one circle at a time', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('f(x) = (4/π)·Σ sin(n·x)/n, n = 1, 3, 5, ...', font_size=30, color=WHITE)
        _intro_watch = Text("Watch: each round adds one rotating circle; the new\ncurve is drawn over the last one's ghost.", font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.0)
        self.wait(1.8)
        self.play(FadeOut(_intro), run_time=0.5)

        harmonics = [1, 3, 5, 7, 9]
        overshoots = [13.7, 10.0, 9.4, 9.2, 9.1]
        center = np.array([-4.2, -0.3, 0.0])
        unit = 1.05
        axes = Axes(x_range=[0, 2 * PI, PI / 2], y_range=[-1.5, 1.5, 0.5], x_length=6.2,
                    y_length=3.6, axis_config={"include_tip": False, "stroke_opacity": 0.45}
                    ).move_to([2.9, -0.3, 0])
        title = Text("A square wave, one circle at a time", font_size=32,
                     color=YELLOW).to_edge(UP, buff=0.25)
        target = VGroup(
            DashedLine(axes.c2p(0, 1), axes.c2p(PI, 1), color=GREY_B, dash_length=0.08),
            DashedLine(axes.c2p(PI, 1), axes.c2p(PI, -1), color=GREY_B, dash_length=0.08),
            DashedLine(axes.c2p(PI, -1), axes.c2p(2 * PI, -1), color=GREY_B, dash_length=0.08),
        )
        count = [1]
        t = ValueTracker(0.0)

        def partial(x, terms):
            return sum((4 / PI) * math.sin(n * x) / n for n in harmonics[:terms])

        def chain():
            group = VGroup()
            p = center.copy()
            for n in harmonics[:count[0]]:
                r = unit * 4 / (PI * n)
                group.add(Circle(radius=r, color=GREY_B, stroke_width=1.5,
                                 stroke_opacity=0.5).move_to(p))
                q = p + r * np.array([math.cos(n * t.get_value()), math.sin(n * t.get_value()), 0.0])
                group.add(Line(p, q, color=YELLOW, stroke_width=2.5))
                p = q
            group.add(Dot(p, color=YELLOW, radius=0.05))
            group.add(DashedLine(p, axes.c2p(t.get_value(), partial(t.get_value(), count[0])),
                                 color=GREY_B, stroke_width=1, dash_length=0.06))
            return group

        def trace():
            xs = np.linspace(0, max(t.get_value(), 1e-3), 180)
            curve = VMobject(color=TEAL, stroke_width=3.5)
            curve.set_points_as_corners([axes.c2p(x, partial(x, count[0])) for x in xs])
            return curve

        def label():
            k = count[0]
            return Text(f"round {k}: {k} circle{'s' if k > 1 else ''},  corner overshoot "
                        f"{overshoots[k - 1]:.1f}%", font_size=26, color=WHITE
                        ).move_to([0, -3.2, 0])

        live_chain = always_redraw(chain)
        live_trace = always_redraw(trace)
        live_label = always_redraw(label)
        self.play(FadeIn(title), Create(axes), Create(target), run_time=1.0)
        self.add(live_chain, live_trace, live_label)
        ghosts = VGroup()
        self.add(ghosts)
        count[0] = 1
        t.set_value(0.0)
        self.play(t.animate.set_value(2 * PI), run_time=2.3, rate_func=linear)
        ghosts.add(trace().set_stroke(color=BLUE_D, opacity=0.35, width=2))
        self.wait(0.3)
        count[0] = 2
        t.set_value(0.0)
        self.play(t.animate.set_value(2 * PI), run_time=2.3, rate_func=linear)
        ghosts.add(trace().set_stroke(color=BLUE_D, opacity=0.35, width=2))
        self.wait(0.3)
        count[0] = 3
        t.set_value(0.0)
        self.play(t.animate.set_value(2 * PI), run_time=2.3, rate_func=linear)
        ghosts.add(trace().set_stroke(color=BLUE_D, opacity=0.35, width=2))
        self.wait(0.3)
        count[0] = 4
        t.set_value(0.0)
        self.play(t.animate.set_value(2 * PI), run_time=2.3, rate_func=linear)
        ghosts.add(trace().set_stroke(color=BLUE_D, opacity=0.35, width=2))
        self.wait(0.3)
        count[0] = 5
        t.set_value(0.0)
        self.play(t.animate.set_value(2 * PI), run_time=2.3, rate_func=linear)
        ghosts.add(trace().set_stroke(color=BLUE_D, opacity=0.35, width=2))
        self.wait(0.3)
        corner = Circle(radius=0.35, color=RED).move_to(axes.c2p(0.3142, 1.1))
        gibbs = Text("this bump never shrinks below about 9%: the Gibbs phenomenon",
                     font_size=24, color=RED_B).next_to(axes, UP, buff=0.15)
        self.play(Create(corner), FadeIn(gibbs), run_time=0.9)
        self.wait(1.3)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in self.mobjects:
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(*self.mobjects), run_time=0.8)
        _head = Text('What the animation shows', font_size=34, weight=BOLD, color=YELLOW)
        _eq = Text('f(x) = (4/π)·Σ sin(n·x)/n, n = 1, 3, 5, ...', font_size=28, color=WHITE)
        _facts = VGroup(Text('5 rounds, adding harmonics n = 1, 3, 5, 7, 9', font_size=25, color=GREY_A), Text('Corner overshoot per round: 13.7%, 10.0%, 9.4%, 9.2%, 9.1%', font_size=25, color=GREY_A), Text('The overshoot stalls near 9% of the jump: the Gibbs phenomenon', font_size=25, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _key = Text('Each circle adds finer detail, and the curve approaches the square\nwave everywhere except right at the jumps.', font_size=27, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.42)
        if _card.width > 12.4:
            _card.scale_to_fit_width(12.4)
        if _card.height > 7.0:
            _card.scale_to_fit_height(7.0)
        self.play(FadeIn(_head, shift=0.2 * DOWN), FadeIn(_eq), run_time=1.2)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=4.2)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.2)
        self.wait(3.1)
