"""Generated by AetherLab - numeric trajectory (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Numerical solution of the model', font_size=38, weight=BOLD, color=YELLOW)
        _intro_eq = Text("VC' = (Vs - VC)/(R*C)", font_size=28, color=WHITE)
        _intro_watch = Text('Watch: the tracer draws VC(t) as time advances left to\nright.', font_size=24, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 6.0:
            _intro.scale_to_fit_height(6.0)
        _intro_bg = SurroundingRectangle(_intro, color=BLUE_E, buff=0.45, corner_radius=0.15,
                                         stroke_width=2, fill_color=BLACK, fill_opacity=0.35)
        _intro_grp = VGroup(_intro_bg, _intro)

        self.play(FadeIn(_intro_grp, shift=0.2 * UP), run_time=1.0)
        self.wait(3.0)
        self.play(FadeOut(_intro_grp), run_time=0.5)

        xs = [0.0, 4e-05, 8e-05, 0.00013, 0.00017, 0.00021, 0.00025, 0.00029, 0.00034, 0.00038, 0.00042, 0.00046, 0.0005, 0.00055, 0.00059, 0.00063, 0.00067, 0.00071, 0.00076, 0.0008, 0.00084, 0.00088, 0.00092, 0.00097, 0.00101, 0.00105, 0.00109, 0.00113, 0.00118, 0.00122, 0.00126, 0.0013, 0.00134, 0.00139, 0.00143, 0.00147, 0.00151, 0.00155, 0.0016, 0.00164, 0.00168, 0.00172, 0.00176, 0.00181, 0.00185, 0.00189, 0.00193, 0.00197, 0.00202, 0.00206, 0.0021, 0.00214, 0.00218, 0.00223, 0.00227, 0.00231, 0.00235, 0.00239, 0.00244, 0.00248, 0.00252, 0.00256, 0.00261, 0.00265, 0.00269, 0.00273, 0.00277, 0.00282, 0.00286, 0.0029, 0.00294, 0.00298, 0.00303, 0.00307, 0.00311, 0.00315, 0.00319, 0.00324, 0.00328, 0.00332, 0.00336, 0.0034, 0.00345, 0.00349, 0.00353, 0.00357, 0.00361, 0.00366, 0.0037, 0.00374, 0.00378, 0.00382, 0.00387, 0.00391, 0.00395, 0.00399, 0.00403, 0.00408, 0.00412, 0.00416, 0.0042, 0.00424, 0.00429, 0.00433, 0.00437, 0.00441, 0.00445, 0.0045, 0.00454, 0.00458, 0.00462, 0.00466, 0.00471, 0.00475, 0.00479, 0.00483, 0.00487, 0.00492, 0.00496, 0.005]
        ys = [0.0, 0.41146, 0.806, 1.1843, 1.54703, 1.89484, 2.22834, 2.54811, 2.85473, 3.14873, 3.43064, 3.70094, 3.96012, 4.20864, 4.44694, 4.67542, 4.89451, 5.10458, 5.30601, 5.49915, 5.68435, 5.86192, 6.03219, 6.19545, 6.35199, 6.50209, 6.64602, 6.78402, 6.91635, 7.04323, 7.16489, 7.28154, 7.3934, 7.50065, 7.60349, 7.7021, 7.79665, 7.88731, 7.97424, 8.05759, 8.13751, 8.21415, 8.28763, 8.35809, 8.42565, 8.49042, 8.55254, 8.6121, 8.6692, 8.72396, 8.77646, 8.82681, 8.87508, 8.92137, 8.96575, 9.0083, 9.04911, 9.08823, 9.12575, 9.16172, 9.19621, 9.22929, 9.261, 9.29141, 9.32056, 9.34852, 9.37533, 9.40103, 9.42567, 9.44931, 9.47196, 9.49369, 9.51452, 9.5345, 9.55365, 9.57202, 9.58963, 9.60651, 9.6227, 9.63823, 9.65311, 9.66739, 9.68107, 9.6942, 9.70678, 9.71884, 9.73041, 9.7415, 9.75214, 9.76234, 9.77212, 9.78149, 9.79049, 9.79911, 9.80737, 9.8153, 9.8229, 9.83018, 9.83717, 9.84387, 9.8503, 9.85646, 9.86236, 9.86803, 9.87346, 9.87866, 9.88366, 9.88844, 9.89303, 9.89743, 9.90165, 9.9057, 9.90958, 9.9133, 9.91687, 9.92029, 9.92357, 9.92671, 9.92973, 9.93262]

        # Shortened title that fits comfortably inside the safe frame width.
        title = Text('RC charging: VC(t)', font_size=36, weight=BOLD, color=YELLOW).to_edge(UP, buff=0.35)

        x_min, x_max = min(xs), max(xs)
        y_min, y_max = min(ys), max(ys)
        if y_max - y_min < 1e-9:
            y_min, y_max = y_min - 1.0, y_max + 1.0
        y_pad = (y_max - y_min) * 0.18

        # Y-axis goes 0 -> ~10 (volts), X-axis goes 0 -> 0.005 (seconds).
        axes = Axes(
            x_range=[0.0, 0.005, 0.001],
            y_range=[0.0, 10.0 + y_pad, 2.0],
            x_length=10,
            y_length=5.4,
            tips=False,
            axis_config={
                "stroke_color": GREY_B,
                "stroke_width": 2,
                "include_tip": False,
            },
        ).to_edge(DOWN, buff=0.7)
        x_axis_label = Text("t (s)", font_size=24, color=GREY_B).next_to(axes.x_axis.get_end(), DOWN, buff=0.2)
        y_axis_label = Text('VC (V)', font_size=24, color=GREY_B).next_to(axes.y_axis.get_end(), LEFT, buff=0.2)

        # Numeric tick labels at sensible round values so the curve is readable.
        x_tick_labels = VGroup(*[
            Text(f"{v:g}", font_size=18, color=GREY_B)
            .next_to(axes.x_axis.n2p(v), DOWN, buff=0.18)
            for v in [0.0, 0.001, 0.002, 0.003, 0.004, 0.005]
        ])
        y_tick_labels = VGroup(*[
            Text(f"{v:g}", font_size=18, color=GREY_B)
            .next_to(axes.y_axis.n2p(v), LEFT, buff=0.18)
            for v in [0, 2, 4, 6, 8, 10]
        ])

        # Use floats for the curve builder so Mobject coordinates stay smooth.
        points = [axes.coords_to_point(float(x), float(y)) for x, y in zip(xs, ys)]
        curve = VMobject(color=BLUE_C, stroke_width=4)
        curve.set_points_as_corners(points)
        curve.set_z_index(3)

        tracer = Dot(points[0], color=YELLOW_E, radius=0.09, stroke_width=2,
                     stroke_color=BLACK).set_z_index(5)
        tracer_trail = TracedPath(tracer.get_center, stroke_color=YELLOW_E,
                                  stroke_width=2, stroke_opacity=0.55).set_z_index(2)

        def point_at_time(alpha):
            position = np.clip(alpha, 0.0, 1.0) * (len(points) - 1)
            index = min(int(position), len(points) - 2)
            fraction = position - index
            return points[index] + fraction * (points[index + 1] - points[index])

        # Build the scaffolding so frame 1 is never a black screen.
        scaffolding = VGroup(axes, x_axis_label, y_axis_label,
                             x_tick_labels, y_tick_labels)
        self.play(FadeIn(title, shift=0.2 * DOWN), run_time=0.8)
        self.play(Create(axes), FadeIn(x_axis_label), FadeIn(y_axis_label),
                  LaggedStart(*[FadeIn(lbl, scale=0.6) for lbl in x_tick_labels],
                              lag_ratio=0.18),
                  LaggedStart(*[FadeIn(lbl, scale=0.6) for lbl in y_tick_labels],
                              lag_ratio=0.18),
                  run_time=1.4)

        asymptote = DashedLine(
            start=axes.coords_to_point(x_min, 10.0),
            end=axes.coords_to_point(x_max, 10.0),
            color=GREY_A,
            stroke_width=2,
            dash_length=0.12,
        ).set_z_index(1)
        asymptote_lbl = Text('Vs = 10 V', font_size=20, color=GREY_A).next_to(
            axes.coords_to_point(x_max * 0.55, 10.0), UP, buff=0.12
        ).set_z_index(4)
        self.play(Create(asymptote), FadeIn(asymptote_lbl), run_time=0.8)

        self.play(Create(curve), run_time=3.0)
        self.add(tracer_trail, tracer)
        self.play(
            UpdateFromAlphaFunc(
                tracer,
                lambda mob, alpha: mob.move_to(point_at_time(alpha)),
                rate_func=linear,
            ),
            run_time=2.5,
        )

        # Living ending: highlight the final state with new information,
        # so frames 4-6 keep changing.
        end_time_val = xs[-1]
        end_vc_val = ys[-1]
        end_point = axes.coords_to_point(end_time_val, end_vc_val)
        end_marker = Cross(stroke_color=YELLOW_E, stroke_width=3).scale(0.18).move_to(end_point)
        end_marker.set_z_index(6)
        end_value_lbl = Text(
            f"VC(0.005) = {end_vc_val:.2f} V",
            font_size=26, color=YELLOW_E, weight=BOLD
        ).next_to(end_point, UP, buff=0.25)

        self.play(Create(end_marker), FadeIn(end_value_lbl, shift=0.15 * UP), run_time=0.7)

        tau_marker = DashedLine(
            start=axes.coords_to_point(0.001, 0.0),
            end=axes.coords_to_point(0.001, 6.32),
            color=GREEN_E, stroke_width=2, dash_length=0.1
        ).set_z_index(2)
        tau_lbl = Text(r'$\tau$ = 1 ms', font_size=22, color=GREEN_E).next_to(
            axes.coords_to_point(0.001, 6.32), UP, buff=0.15
        ).set_z_index(4)
        self.play(Create(tau_marker), FadeIn(tau_lbl), run_time=0.7)

        residual = Text(
            "Residual to Vs: 0.07 V (~0.7%)",
            font_size=22, color=GREY_A,
        ).next_to(end_value_lbl, DOWN, buff=0.18)
        self.play(FadeIn(residual, shift=0.1 * UP), run_time=0.6)
        self.wait(1.2)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in list(self.mobjects):
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(Group(*self.mobjects)), run_time=0.8)

        _head = Text('What the animation shows', font_size=32, weight=BOLD, color=YELLOW)
        _eq = Text("VC' = (Vs - VC)/(R*C)", font_size=26, color=WHITE)
        _facts = VGroup(
            Text('VC starts at 0 V and reaches 9.93 V at t = 0.005 s', font_size=22, color=GREY_A),
            Text('Largest |VC| reached: 9.93 V (asymptote Vs = 10 V)', font_size=22, color=GREY_A),
            Text('Parameters: Vs = 10 V, R = 1000 ohm, C = 1 muF, tau = 0.001 s',
                 font_size=22, color=GREY_A),
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.28)
        _key = Text(
            'Every point on the curve comes from integrating the equations above\nnumerically, not from a sketch.',
            font_size=23, color=TEAL_A,
        )
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.38)
        if _card.width > 12.0:
            _card.scale_to_fit_width(12.0)
        if _card.height > 6.5:
            _card.scale_to_fit_height(6.5)
        _card_bg = SurroundingRectangle(_card, color=BLUE_E, buff=0.45, corner_radius=0.15,
                                        stroke_width=2, fill_color=BLACK, fill_opacity=0.3)
        _card_full = VGroup(_card_bg, _card)

        self.play(FadeIn(_card_full, shift=0.2 * DOWN), run_time=1.2)
        self.wait(6.0)