"""Generated by AetherLab - standing wave (curated component)."""

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Standing wave: normal mode n = 3', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('y(x,t) = 2A·sin(nπx/L)·cos(ωt)', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: the nodes stay still while the string breathes\nbetween the dashed envelopes.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.2)
        self.wait(3.5)
        self.play(FadeOut(_intro), run_time=0.6)

        n = 3
        title = Text('Show a standing wave forming from two travelling waves on a…').scale(0.46).to_edge(UP)

        length = 10.0
        amp = 1.4
        x0 = -length / 2.0

        def y_of(x, phase):
            xi = x - x0
            return amp * np.sin(n * PI * xi / length) * np.cos(phase)

        axis = Line([x0, 0, 0], [x0 + length, 0, 0], color=GREY_B,
                    stroke_width=2, stroke_opacity=0.5)
        wall_l = Line([x0, -1.8, 0], [x0, 1.8, 0], color=GREY_A, stroke_width=5)
        wall_r = Line([x0 + length, -1.8, 0], [x0 + length, 1.8, 0], color=GREY_A, stroke_width=5)

        grid = np.linspace(x0, x0 + length, 160)
        phase = ValueTracker(0.0)

        def string():
            pts = [np.array([x, y_of(x, phase.get_value()), 0.0]) for x in grid]
            m = VMobject(color=TEAL, stroke_width=4)
            m.set_points_smoothly(pts)
            return m

        wave = always_redraw(string)
        # Envelope (the standing-wave amplitude profile) as a dashed ghost.
        env_hi = DashedVMobject(VMobject(color=BLUE_C, stroke_width=2).set_points_smoothly(
            [np.array([x, abs(amp * np.sin(n * PI * (x - x0) / length)), 0.0]) for x in grid]))
        env_lo = DashedVMobject(VMobject(color=BLUE_C, stroke_width=2).set_points_smoothly(
            [np.array([x, -abs(amp * np.sin(n * PI * (x - x0) / length)), 0.0]) for x in grid]))

        # Nodes (fixed) and antinodes (max swing).
        nodes = VGroup(*[Dot([x0 + length * k / n, 0, 0], color=RED, radius=0.07)
                         for k in range(n + 1)])
        antinodes = VGroup(*[Dot([x0 + length * (k + 0.5) / n, 0, 0], color=YELLOW, radius=0.06)
                             for k in range(n)])
        node_lbl = Text("nodes (fixed)", color=RED).scale(0.3).to_corner(DL, buff=0.6)

        self.play(FadeIn(title), Create(axis), Create(wall_l), Create(wall_r), run_time=1.0)
        self.play(Create(env_hi), Create(env_lo), run_time=0.9)
        self.add(wave)
        self.play(LaggedStart(*[GrowFromCenter(d) for d in nodes], lag_ratio=0.1),
                  FadeIn(node_lbl), run_time=1.0)
        self.add(antinodes)
        self.play(phase.animate.set_value(3.0 * TAU), run_time=6.0, rate_func=linear)
        self.wait(0.4)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in self.mobjects:
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(*self.mobjects), run_time=0.8)
        _head = Text('What the animation shows', font_size=34, weight=BOLD, color=YELLOW)
        _eq = Text('y(x,t) = 2A·sin(nπx/L)·cos(ωt)', font_size=28, color=WHITE)
        _facts = VGroup(Text('Mode n = 3: 4 nodes (including the fixed ends) and 3 antinodes', font_size=25, color=GREY_A), Text('Wavelength λ = 2L/n = 0.67·L', font_size=25, color=GREY_A), Text('Frequency f = n·f₁ = 3·f₁', font_size=25, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _key = Text('Two equal waves travelling in opposite directions add up to a standing\nwave. Only whole numbers of half-wavelengths fit: L = n·λ/2.', font_size=27, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.42)
        if _card.width > 12.4:
            _card.scale_to_fit_width(12.4)
        if _card.height > 7.0:
            _card.scale_to_fit_height(7.0)
        self.play(FadeIn(_head, shift=0.2 * DOWN), FadeIn(_eq), run_time=1.2)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=4.2)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.2)
        self.wait(8.0)
