"""Generated by AetherLab (deterministic oscillator template)."""

import math

import numpy as np

from manim import *

config.background_color = "#0A0A0F"


class AetherLabScene(Scene):
    def construct(self):
        TXT = '#F8FAFC'
        title = Text('About 10.1% of the muons created 15 km up at v=0.995c reach the ground', color=TXT).scale(0.5)
        title.to_edge(UP)
        summary = Text('About 10.1% of the muons created 15 km up at v=0.995c reach the ground. Time dilation (γ≈10.01) stretches t...', color=TXT).scale(0.3)
        summary.next_to(title, DOWN, buff=0.15)
        steps = [
            'Compute the Lorentz factor for v = 0.995c.',
            'Compute the proper time the muon accumulates while traversing L = 15 km in the...',
            'Count how many half-lives fit in that proper time.'
        ]
        rows = VGroup(*[Text(f"{i}. {s}", color=TXT).scale(0.24) for i, s in enumerate(steps, 1)])
        rows.arrange(DOWN, aligned_edge=LEFT, buff=0.12)
        rows.next_to(summary, DOWN, buff=0.2)
        self.add(title, summary, rows)

        axes = Axes(x_range=[-3, 3, 1], y_range=[-2, 2, 1]).scale(0.5)
        axes.to_edge(DOWN)
        damping = ValueTracker(0.15)
        stiffness = ValueTracker(1.0)

        def curve_fn():
            d = damping.get_value()
            k = stiffness.get_value()
            fn = lambda x: math.exp(-d * (x + 3)) * math.sin(k * x * 2)
            if hasattr(axes, "plot"):
                return axes.plot(fn, color='#06B6D4')
            return axes.get_graph(fn, color='#06B6D4')

        curve = always_redraw(curve_fn)
        self.add(axes)
        self.play(Create(curve_fn()), run_time=1.50)
        self.add(curve)
        self.play(damping.animate.set_value(0.5499999999999999), run_time=2.50,
                  rate_func=there_and_back)
        self.wait(1)
