"""Generated by AetherLab - Fourier epicycles (curated component)."""

import math

import numpy as np
from manim import *


class AetherLabScene(Scene):
    def construct(self):
        # AetherLab explanation layer: concept, governing equation, what to watch.
        _intro_head = Text('Building a square wave from sine waves', font_size=40, weight=BOLD, color=YELLOW)
        _intro_eq = Text('f(x) = (4/π)·Σ sin(n·x)/n, n = 1, 3, 5, ...', font_size=30, color=WHITE)
        _intro_watch = Text('Watch: each rotating circle is one harmonic; the tip\nof the chain draws the wave.', font_size=26, color=GREY_B)
        _intro = VGroup(_intro_head, _intro_eq, _intro_watch).arrange(DOWN, buff=0.5)
        if _intro.width > 12.4:
            _intro.scale_to_fit_width(12.4)
        if _intro.height > 7.0:
            _intro.scale_to_fit_height(7.0)
        self.play(FadeIn(_intro, shift=0.2 * UP), run_time=1.2)
        self.wait(3.3)
        self.play(FadeOut(_intro), run_time=0.6)

        harmonics = [1, 3, 5, 7, 9]
        amps = [4.0 / (math.pi * k) for k in harmonics]
        center = np.array([-3.6, 0.0, 0.0])

        title = Text('Build intuition for Fourier series by adding sine harmonics.').scale(0.46).to_edge(UP)

        def chain(tt):
            group = VGroup()
            p = center.copy()
            for k, a in zip(harmonics, amps):
                ang = k * tt
                nxt = p + a * np.array([math.cos(ang), math.sin(ang), 0.0])
                group.add(Circle(radius=a, color=GREY_B, stroke_width=1.5, stroke_opacity=0.35).move_to(p))
                group.add(Line(p, nxt, color=YELLOW, stroke_width=2.5))
                p = nxt
            return group, p

        def tip(tt):
            return chain(tt)[1]

        def wave_value(tt):
            return float(sum(a * math.sin(k * tt) for k, a in zip(harmonics, amps)))

        axes = Axes(
            x_range=[0.0, 2.0 * math.pi, math.pi / 2.0],
            y_range=[-1.4, 1.4, 0.5],
            x_length=5.5, y_length=3.2,
            axis_config={"include_tip": False, "stroke_opacity": 0.5},
        ).shift(RIGHT * 2.4)
        target = axes.plot(lambda x: sum(a * math.sin(k * x) for k, a in zip(harmonics, amps)),
                           x_range=[0.0, 2.0 * math.pi], color=BLUE_C)

        t = ValueTracker(0.0)
        phasors = always_redraw(lambda: chain(t.get_value())[0])
        pen = always_redraw(lambda: Dot(tip(t.get_value()), color=YELLOW, radius=0.05))
        drawing = TracedPath(lambda: tip(t.get_value()), stroke_color=TEAL, stroke_width=2.5)
        wave_dot = always_redraw(lambda: Dot(
            axes.c2p(t.get_value(), wave_value(t.get_value())), color=YELLOW, radius=0.06))
        link = always_redraw(lambda: DashedLine(
            tip(t.get_value()),
            axes.c2p(t.get_value(), wave_value(t.get_value())),
            color=GREY_B, stroke_width=1.5, dash_length=0.08))

        self.play(FadeIn(title), Create(axes), run_time=1.0)
        self.add(phasors, drawing, pen, link, wave_dot)
        self.play(t.animate.set_value(2.0 * math.pi), Create(target),
                  run_time=8.0, rate_func=linear)
        self.wait(0.5)

        # AetherLab explanation layer: clear the stage, then explain what it showed.
        for _m in self.mobjects:
            _m.clear_updaters()
        if self.mobjects:
            self.play(FadeOut(*self.mobjects), run_time=0.8)
        _head = Text('What the animation shows', font_size=34, weight=BOLD, color=YELLOW)
        _eq = Text('f(x) = (4/π)·Σ sin(n·x)/n, n = 1, 3, 5, ...', font_size=28, color=WHITE)
        _facts = VGroup(Text('5 odd harmonics are used: n = 1, 3, 5, 7, 9', font_size=25, color=GREY_A), Text('Circle n has radius 4/(π·n): higher harmonics add finer detail', font_size=25, color=GREY_A), Text('Near the jumps the sum overshoots by about 9% (the Gibbs phenomenon)', font_size=25, color=GREY_A)).arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _key = Text('Enough rotating circles can draw any repeating shape. A square wave\nneeds only the odd harmonics.', font_size=27, color=TEAL_A)
        _key_box = SurroundingRectangle(_key, color=TEAL, buff=0.22, corner_radius=0.12)
        _card = VGroup(_head, _eq, _facts, VGroup(_key, _key_box)).arrange(DOWN, buff=0.42)
        if _card.width > 12.4:
            _card.scale_to_fit_width(12.4)
        if _card.height > 7.0:
            _card.scale_to_fit_height(7.0)
        self.play(FadeIn(_head, shift=0.2 * DOWN), FadeIn(_eq), run_time=1.2)
        self.play(LaggedStart(*[FadeIn(_f, shift=0.2 * RIGHT) for _f in _facts], lag_ratio=0.85), run_time=4.2)
        self.play(FadeIn(_key), Create(_key_box), run_time=1.2)
        self.wait(8.0)
